### ISSUE TITLE
ToInputs is failing for array of objects

### ISSUE THREAD

**Issue by rahuljadhav** [graphql-dotnet/graphql-dotnet#102]
Hi,

For example:
if used variable for mutation with array of primitive types it works 
 "{'input': {'a':'foo', 'b':**['bar']**, 'c': 'baz'} }".ToInputs()

but in case of array of object it fails:

"{'input': {'a':'foo', 'b':**[{'x':'bar'}]**, 'c': 'baz'} }".ToInputs()
 which gives following exception:

``
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in :line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in :line 0
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in :line 0
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in :line 0
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType) in :line 0
   at Newtonsoft.Json.Linq.JToken.ToObject[T]() in :line 0
   at GraphQL.StringExtensions.<>c.<GetValue>b__3_0(List`1 list, JToken token) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 44
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at GraphQL.StringExtensions.GetValue(Object value) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 41
   at GraphQL.StringExtensions.ToDictionary(String json) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 24
   at GraphQL.StringExtensions.GetValue(Object value) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 36
   at GraphQL.StringExtensions.ToDictionary(String json) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 24
   at GraphQL.StringExtensions.ToInputs(String json) in C:\Home\projects\graphql-dotnet\src\GraphQL\StringExtensions.cs:line 17
``

Please help to resolve it.

Thanks & Regards,
Rahul

**Comment by joemcbride** [comment]
This appears to be working on the latest version.  Which version are you currently running?  Can you upgrade and re-test?  Thanks.

**Comment by rahuljadhav** [comment]
We are using 0.5.1 version. It is working fine in current version. 
Thanks for quick reply.

**Comment by joemcbride** [comment]
👍
