### ISSUE TITLE
No service for type 'GraphQL.Types.ObjectGraphType' has been registered.

### ISSUE THREAD

**Issue by SirwanAfifi** [graphql-dotnet/graphql-dotnet#1044]
I have the following query:
```csharp
FieldAsync<ObjectGraphType>(
    "login",
    arguments: new QueryArguments(
        new QueryArgument<NonNullGraphType<StringGraphType>>{ Name = "userName" }, 
        new QueryArgument<NonNullGraphType<StringGraphType>>{ Name = "password" }),
    resolve: async context =>
    {
        var userName = context.GetArgument<string>("userName");
        var password = context.GetArgument<string>("password");

        var user = await userManager.FindByNameAsync(userName);
        if (user != null)
        {
            var result = await signInManager.CheckPasswordSignInAsync(user, password, false);
            if (result.Succeeded)
            {

                var claims = new[]
                {
                    new Claim(JwtRegisteredClaimNames.Sub, user.Email),
                    new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
                };

                var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(config["Tokens:Key"]));
                var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);

                var token = new JwtSecurityToken(config["Tokens:Issuer"],
                    config["Tokens:Issuer"],
                    claims,
                    expires: DateTime.Now.AddMinutes(30),
                    signingCredentials: creds);

                return new { token = new JwtSecurityTokenHandler().WriteToken(token), userId = user.Id };
            }
        }
        return "Could not create token";
    });
```

When I try to test this query in Playground UI, I get the following exception message:

```
 GraphQL execution error(s): GraphQL.ExecutionError: No service for type 'GraphQL.Types.ObjectGraphType' has been registered. ---> System.InvalidOperationException: No service for type 'GraphQL.Types.ObjectGraphType' has been registered.
         at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
         at GraphQL.Types.Schema.<CreateTypesLookup>b__56_0(Type t)
         at System.Linq.Enumerable.SelectListIterator`2.ToList()
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at GraphQL.Types.Schema.CreateTypesLookup()
         at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
         at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
         at System.Lazy`1.CreateValue()
         at GraphQL.Types.Schema.get_AllTypes()
         at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)
         at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
         --- End of inner exception stack trace ---
```

I have also tried to register this type inside Schema but it didn't work:
```csharp
namespace My.Api.GraphQL
{
    public class MySchema : Schema
    {
        public MySchema(IDependencyResolver resolver): base(resolver)
        {
            Query = resolver.Resolve<MyQuery>();
            RegisterType<ObjectGraphType>();
        }
    }
}
```

**Comment by joemcbride** [comment]
```csharp
FieldAsync<ObjectGraphType>(...)
```

This is not valid.  You need to create a GraphType that represents the response from your resolver.  GraphQL has a strongly typed Schema.  Your resolver is currently returning both a string and an anonymous object with a `token` string property.  That is also not valid.  You have to return the same datatype.

See the introduction on the GraphType first approach.  https://graphql-dotnet.github.io/docs/getting-started/introduction#graphtype-first-approach


```csharp
public class TokenResult : ObjectGraphType
{
  public TokenResult()
  {
    Field<StringGraphType>("token");
    Field<StringGraphType>("error");
  }
}

FieldAsync<TokenResultType>("login", ...)
```

So the shape of the data returned in your `login` field is required to be an object with `token` and `error` properties.

**Comment by SirwanAfifi** [comment]
Thanks. one more thing, How can we use built-in types for our fields? things like `ULongGraphType` or `GuidGraphType`.  

```csharp
public class CreateEntityInput : InputObjectGraphType
{
    public CreateEntityInput()
    {
        Name = "CreateEntityInput";
        Field<StringGraphType>("Id");
        Field<NonNullGraphType<StringGraphType>>("Name");
        Field<NonNullGraphType<ULongGraphType>>("LonCentre");
        Field<NonNullGraphType<ULongGraphType>>("LatCentre");
        Field<NonNullGraphType<ULongGraphType>>("SizeHa");
    }
}
```
