### ISSUE TITLE
Return ExecutionResult[] not support anymore since Version 2.3. How to handle Batch Queries in Verison 2.3+ ?

### ISSUE THREAD

**Issue by mahald** [graphql-dotnet/graphql-dotnet#1128]
## Summary

Up to Version 2.2 It was possible to return a ExecutionResult[] (as an object), this is not possible anymore since Version 2.3 (I suspect #798 to have broken support for this).

This was very handy as I'm using the Angular Apollo-Client which supports query batch without any code change (i just need to use apollo-angular-link-http-batch instead of apollo-angular-link-http)

This did work perfectly fine until Version 2.3. Is there any (handy) way to do this in Version 2.3+ ? Or is there any possibility to get support for this in Version 2.3+ again ?

PS: I also tried 3.0.0-preview-1141 Version with the same result.

Since Version 2.3 I get the error messages: 

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Expected value to be a GraphQL.ExecutionResult, got GraphQL.ExecutionResult[]
   at GraphQL.Http.DocumentWriter.Write(Object value)
   at GraphQL.Middleware.GraphQLMiddleware.Invoke(HttpContext context) in D:\mh\OfficeGit\csf\dotnet\dotnetLib\GraphQL.Middleware\GraphQLMiddleware.cs:line 60
   at GraphQL.Middleware.GraphQLMiddleware.Invoke(HttpContext context) in D:\mh\OfficeGit\csf\dotnet\dotnetLib\GraphQL.Middleware\GraphQLMiddleware.cs:line 74

```
### Basic example

Down in the code example u find the middleware I'm using.
As u see I'm returning an object in the function  `private async Task<object> ExecuteAsync(HttpContext context)` if `if (requestBodyText[0] == '[')` is true I return an `ExectuionResult[]` if not i return an `ExectionResult `
I also tried to use a List<ExecutionResult> instead.

```

using System;
using System.IO;
using System.Threading.Tasks;
using GraphQL.Http;
using GraphQL.Types;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using GraphQL.Validation;
using Coco;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace GraphQL.Middleware
{
    public sealed class GraphQLMiddleware
    {
        private readonly string grpahiqlPath;
        private readonly Boolean useGraphiql;
        private readonly string graphqlPath;
        private readonly RequestDelegate next;
        private readonly ISchema schema;
        private readonly Boolean exposeExceptions;
        private readonly IValidationRule[] ValidationRules;

        public GraphQLMiddleware(RequestDelegate next , IOptions<GraphQLOptions> options)
        {
            this.next = next ?? throw new ArgumentNullException(nameof(next));
            var optionsValue = options?.Value ?? throw new ArgumentNullException(nameof(options));
            schema = optionsValue?.Schema ?? throw new ArgumentException("Schema is null");
            graphqlPath = optionsValue.GraphQLPath;
            grpahiqlPath = optionsValue.GrpahiQLPath;
            useGraphiql = optionsValue.useGraphiQL;
            exposeExceptions = optionsValue.exposeExceptions;
            ValidationRules = optionsValue.ValidationRules;
        }

        public async Task Invoke(HttpContext context)
        { 
            if (context?.Request?.Path.Equals(graphqlPath) ?? throw new ArgumentNullException(nameof(context)))
            {
                if (string.Equals(context.Request.Method, "POST", StringComparison.OrdinalIgnoreCase))
                {
                    var executionResult = await ExecuteAsync(context).ConfigureAwait(false);
                    context.Response.ContentType = "application/json";
                    context.Response.StatusCode = 200;
                    await context.Response.WriteAsync(new DocumentWriter().Write(executionResult));
                    return;
                }
            }

            if (useGraphiql && string.Equals(context.Request.Method, "GET", StringComparison.OrdinalIgnoreCase))
            {
                if  (context.Request.Path.Equals(graphqlPath) || context.Request.Path.Equals(grpahiqlPath))
                {
                    await GraphiQL.ReplyWithGraphiQLAsync(context.Response, graphqlPath);
                    return;
                }
            }

            await next(context).ConfigureAwait(false);
        }

        async Task<ExecutionResult> Exec(GraphQLRequest graphqlRequest, HttpContext context)
        {
            return await new DocumentExecuter().ExecuteAsync(_ =>
            {
                _.Schema = schema;
                _.Query = graphqlRequest.Query;
                _.Inputs = graphqlRequest.Variables?.ToInputs();
                _.OperationName = graphqlRequest.OperationName;
                _.UserContext = context;
                _.ValidationRules = ValidationRules;
                _.ExposeExceptions = exposeExceptions;
            }).ConfigureAwait(false);
        }

        private async Task<object> ExecuteAsync(HttpContext context)
        {
            string requestBodyText;
            using (var streamReader = new StreamReader(context.Request.Body))
            {
                requestBodyText = await streamReader.ReadToEndAsync().ConfigureAwait(false);
            }

            if (requestBodyText[0] == '[')
            {
                var graphqlRequests = JsonConvert.DeserializeObject<JObject[]>(requestBodyText);
                ExecutionResult[] results = new ExecutionResult[graphqlRequests.Length];

                int i = 0;
                foreach (var graphqlRequestJ in graphqlRequests)
                {
                    var txtThisQuery = graphqlRequestJ.ToString();
                    var graphqlRequest = JsonConvert.DeserializeObject<GraphQLRequest>(txtThisQuery);
                    var result = await Exec(graphqlRequest, context);
                    results[i++] = result;
                }
                return results;
            }
            else
            {
                var graphqlRequest = JsonConvert.DeserializeObject<GraphQLRequest>(requestBodyText);
                var result = await Exec(graphqlRequest, context);
                return result;
            }

        }
    }
}
```

Thats how a batch query looks like:
```
[
    {
        "operationName": "something",
        "variables": {
            "id": "x2df2311-a2a2-4234-9ghf-4de0c34f4x98"
        },
        "query": "query something($id: ID) {\n  ....."
    },
    {
        "operationName": "some_other_thing",
        "variables": {
            "id": "x2df2311-a2a2-4234-9ghf-4de0c34f4x98"
        },
        "query": "query some_other_thing($id: ID) ...."
    }
]
```

And this is how a reply looks link in 2.2:

```
[
    {
        "data": {
            "items": {
                "id": "x2df2311-a2a2-4234-9ghf-4de0c34f4x98",
                "items": [
                    {
                        "value": "xxxxxx",
                        "label": "xxxxx",
                        "xxx": "xxxx",
                        "__typename": "xxxxx"
                    },
                    {
                        "value": "xxxx",
                        "label": "xxxxx",
                        "xxx": "xxxxx",
                        "__typename": "xxx"
                    }
                ],
                "__typename": "xxxx"
            }
        }
    },
    {
        "data": {
            "items": {
                "id": "xxxxxx",
                "items": [
                    {
                        "value": "xxxxxx",
                        "label": "xxxx",
                        "__typename": "xxxx"
                    }
                ],
                "__typename": "xxxx"
            }
        }
    }
]
```

### Motivation

I'm doing a bunch of small queries at the same time, it's better to batch them up into 2-3 quries rather than 20 queries. This notably increased performance.

**Comment by mahald** [comment]
I'm currently stuck at Version 2.4 because of this, is there no way to achieve this ?

**Comment by sungam3r** [comment]
Hey! I would like to make a few comments:
1) This issue is related to another project - https://github.com/graphql-dotnet/server , which solves the problem of transport over HTTP.
2) Although the desired behavior is completely clear to me and I have nothing against the support of batch requests, it seems to me that this goes somewhat against the specification. On the other hand, these are only my concerns, since each transport can transmit requests in an arbitrary manner.
3) See graphql-dotnet/server#241

**Comment by sungam3r** [comment]
By the way, you can also try to solve the task of batch requests using field aliases, but it seems to me that this will not be convenient.

**Comment by sungam3r** [comment]
https://blog.apollographql.com/query-batching-in-apollo-63acfd859862
