### ISSUE TITLE
Dependency Injection Failure using Autofac

### ISSUE THREAD

**Issue by cable729** [graphql-dotnet/graphql-dotnet#113]
When upgrading from 0.8.1 to 0.8.2, I run into the following error.

I use AutoFac to register dependency injection like follows:

```
        public StarWarsSchema(IComponentContext context, StarWarsQuery query)
            : base(type => (GraphType)context.Resolve(type))
        {
            Query = query;
        }
```

When I try to resolve the service using `context.Resolve<IStarWarsSchema>();`, I get a long stack trace (shown at the end). Of course, I am registering the document writer, document executor, schema, query, and all the types.

I'm not sure why AutoFac is trying to do something with QueryArguments, but I'm thinking that the dependency injection built into the GraphQL.DotNet sample may be masking problems since it will create instances if they are not registered.

Autofac.Core.DependencyResolutionException : An exception was thrown while invoking the constructor 'Void .ctor(StarWars.Core.Data.ISomeDAO, StarWars.Core.Data.IOtherDAO)' on type 'StarWarsQuery'. ---> Method not found: 'Void GraphQL.Types.QueryArguments..ctor(GraphQL.Types.QueryArgument[])'. (See inner exception for details.)
  ----> System.MissingMethodException : Method not found: 'Void GraphQL.Types.QueryArguments..ctor(GraphQL.Types.QueryArgument[])'.
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Container.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context)
   at UnitTests.StarWars.GraphQL.StarWarsGraphQLServiceTests.Setup() in C:\Projects\StarWars\GraphQL\StarWarsGraphQLServiceTests.cs:line 28
--MissingMethodException
   at StarWars.GraphQL.StarWarsQuery..ctor(ISomeDAO someDAO, IOtherDAO otherDAO)
   at lambda_method(Closure , Object[] )
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()

**Comment by joemcbride** [comment]
A `params` ctor was added to the `QueryArguments` class.  That is what is probably giving Autofac trouble.

https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/QueryArguments.cs#L8-L11

**Comment by cable729** [comment]
Yeah, could be. Why is the executor requesting that QueryArguments be resolved in the first place though?

**Comment by joemcbride** [comment]
That I'm not sure off-hand, I can take a closer look.

**Comment by cable729** [comment]
It would be good to have some tests around dependency injection. I won't have a chance to look at this until Sunday night, but if it's still open then I can take a crack at it. We should have:

- A failing test(s) that describes this issue
- Tests that ensure this system works with the top C# dependency injection frameworks

**Comment by joemcbride** [comment]
The StarWars tests use the DI feature, granted with just my `SimpleContainer`.  As per supporting specific DI frameworks, I will leave that up to PRs since I don't want to guess at (nor support) what people aren't actually using.

Are you able to post your graph config where you think it is failing?

**Comment by joemcbride** [comment]
Adding a little logging, this is what I see when executing a query that uses arguments.  This example uses only built-in types - `QueryArgument<StringGraphType>` - do your arguments include an object that wants injected data perhaps?

```
------ Test started: Assembly: GraphQL.Tests.dll ------

Query:
{
  human(id: "1") {
    name
    homePlanet
  }
}

Begin Resolving: GraphQL.StarWars.StarWarsSchema
Begin Resolving: GraphQL.StarWars.StarWarsQuery  <-- contains arguments, using each of params and the IEnumerable<T> ctors
Begin Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.StarWarsQuery
End Resolving: GraphQL.StarWars.StarWarsSchema
Begin Resolving: GraphQL.StarWars.Types.CharacterInterface
End Resolving: GraphQL.StarWars.Types.CharacterInterface
Begin Resolving: GraphQL.StarWars.Types.EpisodeEnum
End Resolving: GraphQL.StarWars.Types.EpisodeEnum
Begin Resolving: GraphQL.StarWars.Types.HumanType
Begin Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.Types.HumanType
Begin Resolving: GraphQL.StarWars.Types.DroidType
Begin Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.StarWarsData
End Resolving: GraphQL.StarWars.Types.DroidType

Result:
{
  "data": {
    "human": {
      "name": "Luke",
      "homePlanet": "Tatooine"
    }
  }
}

1 passed, 0 failed, 0 skipped, took 0.79 seconds (Fixie 1.0.0.33).
```

**Comment by joemcbride** [comment]
Tested with an `InputObjectGraphType` that used DI and that worked fine.  Either I don't have the right setup or it is Autofac specific.
