### ISSUE TITLE
Resolver errors in Web API 2

### ISSUE THREAD

**Issue by rkotenko** [graphql-dotnet/graphql-dotnet#1221]
I have been going round and round trying to figure this out.  Using the AspNetWebApi as a base, I have been trying to implement GraphQL into our API.  I created a separate, fresh project, and got started. I can get it to build, but when trying to use GraphiQL to hit it, I get errors about dependency registration.  

To make sure it was not something in the project I did specifically, I tried to run the AspNetWebApi example itself and got the same errors (not pasting them all, just a few):

```
Exception thrown: 'System.InvalidOperationException' in graphql-api.dll
System.InvalidOperationException: No registration for System.Web.Http.Controllers.IHttpActionSelector
   at graphql_api.SimpleContainer.Get(Type serviceType) in C:\Users\koten001\projects\sp\flow-api\graphql-api\SimpleContainer.cs:line 74
   at graphql_api.SimpleResolver.GetService(Type serviceType) in C:\Users\koten001\projects\sp\flow-api\graphql-api\SimpleResolver.cs:line 22
Exception thrown: 'System.InvalidOperationException' in graphql-api.dll
System.InvalidOperationException: No registration for System.Web.Http.Validation.IBodyModelValidator
   at graphql_api.SimpleContainer.Get(Type serviceType) in C:\Users\koten001\projects\sp\flow-api\graphql-api\SimpleContainer.cs:line 74
   at graphql_api.SimpleResolver.GetService(Type serviceType) in C:\Users\koten001\projects\sp\flow-api\graphql-api\SimpleResolver.cs:line 22
Exception thrown: 'System.InvalidOperationException' in graphql-api.dll
```

The only things I changed in the example was the project file for WebApi so it would work in VS 2015 and dropped the Starwars project files straight into the webapi one.  Everything else is the same.

I am using 
VS 2015, 
.net framework 4.6.1
GraphQl-dotnet 2.4.0

I don't see any details about needing to inject System.Web dependencies on MS's site or any graphQL site, so I am really at a loss here.  Any help would be greatly appreciated.

**Comment by rkotenko** [comment]
Never mind. Those errors don't seem to affect the api; they just appear in the debug output.  In my own setup, I had issues with the schema setup, which showed me nothing.  That and the exceptions in the Debug output made me think there was another problem.
