### ISSUE TITLE
Running raw SQL errors out

### ISSUE THREAD

**Issue by nmarun** [graphql-dotnet/graphql-dotnet#1234]
## Description
Raw SQL ignores type null ability

Describe the issue that you're seeing.
I have a bunch of tables that are connected through primary and foreign keys. The contract I've exposed to clients is quite simple. This means I'll have to a few joins internally to get the data requested by clients. Here's how I plan to approach:
1. Build a SQL query based on the tables/sub tables requested by client
2. Call EF to run that single query to fetch denormalized data in one go
3. Convert that to the output structure requested by the client
4. Render JSON.

### Steps to reproduce

To achieve this, I'm trying to understand how GraphQL works internally and I'm going through the source code. I'm getting the below error when I run the query:

```
public class PropertyType : ObjectGraphType<Database.Models.Property>
{
    public PropertyType(IPaymentRepository paymentRepository)
    {
        Field(x => x.Id);
        Field(x => x.Name);
        Field(x => x.Value);
        Field(x => x.City);
        Field(x => x.Family);
        Field(x => x.Street, nullable: true);
        Field<ListGraphType<PaymentType>>("payments",
            arguments: new QueryArguments(new QueryArgument<IntGraphType> {Name = "last"}),
            resolve: context =>
            {
                var lastItemsFilter = context.GetArgument<int?>("last");
                return lastItemsFilter != null
                    ? paymentRepository.GetAllForProperty(context.Source.Id, lastItemsFilter.Value)
                    : paymentRepository.GetAllForProperty(context.Source.Id);
            });
    }
}

public class PropertyRepository : IPropertyRepository
{
    private readonly RealEstateContext _db;

    public PropertyRepository(RealEstateContext db)
    {
        _db = db;
    }

    public IEnumerable<Property> GetFields(IDictionary<string, Field> subFields)
    {
        string sqlQuery = BuildSqlQuery(subFields);
        RawSqlString rawSqlString = new RawSqlString(sqlQuery);
        IQueryable<Property> denormProperties = _db.Properties.FromSql(rawSqlString);
        // when I enumerate the denormProperties variable, I get the below error:
        // "The required column 'Street' was not present in the results of a 'FromSql' operation."
        return null;
    }

    private string BuildSqlQuery(IDictionary<string, Field> subFields)
    {
        // hard coded for now 
        // TODO: build the projection and joins based on value in subFields dictionary
        return "select properties.[Name], properties.City, properties.Family, payments.Id, payments.Paid " +
            "from Properties as properties " +
            "inner join Payments as payments on payments.PropertyId = properties.Id"; 
    }
    ...
}
```

### Expected result

Not sure why 'Street' is considered to be a mandatory field though I've marked it nullable. Also, please let me know if my approach is right.

### Environment

Windows 10, ASP.NET Core 2.0

**Comment by nmarun** [comment]
Interestingly.. my issue number is 1234!

**Comment by sungam3r** [comment]
Please, show stacktrace of your error. It seems that it is not GraphQL related error but EntityFramework error.

**Comment by nmarun** [comment]
@sungam3r , thanks so much. You're right it was an EF-related error. Going through some documentation to understand this error. Please let me know if you can help in any way.

```
System.InvalidOperationException: The required column 'Street' was not present in the results of a 'FromSql' operation.
   at Microsoft.EntityFrameworkCore.Query.Sql.Internal.FromSqlNonComposedQuerySqlGenerator.CreateValueBufferFactory(IRelationalValueBufferFactoryFactory relationalValueBufferFactoryFactory, DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Query.Internal.ShaperCommandContext.NotifyReaderCreated(DbDataReader dataReader)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
```

**Comment by sungam3r** [comment]
It is one of the [limitations](https://docs.microsoft.com/en-us/ef/core/querying/raw-sql#limitations) of `FromSql`.

**Comment by nmarun** [comment]
@sungam3r .. thanks so much for your assistance. Yes, I found out the same as well. I was able to achieve this by calling an ExecuteReader on a command instance.
