### ISSUE TITLE
VERSION : 3.0.0-preview-126, System.MissingMethodException

### ISSUE THREAD

**Issue by eddyjl077** [graphql-dotnet/graphql-dotnet#1304]
2019-Sep-16 15:55:44 [Error] [] Connection id ""0HLPQRUPU2HQ2"", Request id ""0HLPQRUPU2HQ2:00000087"": An unhandled exception was thrown by the application.
System.MissingMethodException: Method not found: 'Void GraphQL.ExecutionOptions.set_SetFieldMiddleware(Boolean)'.
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.GetOptions(String operationName, String query, Inputs variables, IDictionary`2 context, CancellationToken cancellationToken)
   at GraphQL.Server.Internal.DefaultGraphQLExecuter`1.ExecuteAsync(String operationName, String query, Inputs variables, IDictionary`2 context, CancellationToken cancellationToken)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

**Comment by sungam3r** [comment]
`ExecutionOptions.SetFieldMiddleware` was indeed removed and all necessary changes are made to the server project. See graphql-dotnet/server#186. The problem is that I did not find the server packages on nuget.org - see graphql-dotnet/server#239. I still did not understand why they were not pushed.
