### ISSUE TITLE
Nullable<Guid> cannot be coerced error

### ISSUE THREAD

**Issue by fogzot** [graphql-dotnet/graphql-dotnet#1466]
## Description

If a class contains a nullable `Guid`:

```
public class Product
{
    public string Code { get; set; }
    public Guid? DataSheetId { get; set; }
}
```

and one tries to define the corresponding GraphQL type using a specific version of the `Field` method:

```
public class ProductType : ObjectGraphType<Product>
{
    public ProductType(IDataLoaderContextAccessor accessor)
    {
        Name = "Product";
        Field<NonNullGraphType<IdGraphType>>("Code");
        Field(x => x.DataSheetId, nullable: true);
    }
}
```

an exception is thrown **even if `nullable: true` is specified**.

The exception is not thrown (everything works) if a different version of the same method is used:

```
Field<GuidGraphType>("DataSheetId");
```

### Steps to reproduce

Add a nullable `Guid` to any class and define the type as explained above.

### Expected result

The code should not throw an exception.

### Actual result

The following exception is thrown:

```
GraphQL.ExecutionError: The GraphQL type for Field: 'DataSheetId' on parent type: 'Product' could not be derived implicitly. 
 ---> System.ArgumentException: The GraphQL type for Field: 'DataSheetId' on parent type: 'Product' could not be derived implicitly. 
 ---> System.ArgumentOutOfRangeException: Explicitly nullable type: Nullable<Guid> cannot be coerced to a non nullable GraphQL type. 

Parameter name: isNullable
   at GraphQL.TypeExtensions.GetGraphTypeFromType(Type type, Boolean isNullable)
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   --- End of inner exception stack trace ---
   at GraphQL.Types.ComplexGraphType`1.Field[TProperty](String name, Expression`1 expression, Boolean nullable, Type type)
   at Parts.GraphQL.ProductType..ctor(IDataLoaderContextAccessor accessor) in /home/fog/Customers/cellino/parts/parts-api/graphql/ProductType.cs:line 20
```

### Environment

graphql-dotnet 2.4.0
dotnet core 2.1

**Comment by sungam3r** [comment]
@fogzot Please read [this warning](https://github.com/graphql-dotnet/graphql-dotnet#installation) and try the latest 3.0.0-preview-XXXX version.

**Comment by sungam3r** [comment]
Closed due to inactivity. @fogzot Feel free to reopen if you continue to have problems with this.
