### ISSUE TITLE
Empty array in input type throws error

### ISSUE THREAD

**Issue by bgoerdt** [graphql-dotnet/graphql-dotnet#1569]
## Description

An input type that has an empty array is causing an exception while validating the document in the latest version of the packages. This was working when using GraphQL version 3.0.0-preview-1352, but it is not working when I upgraded to 3.0.0-preview-1490.

The exception is: 
```
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at GraphQL.Language.CoreToVanillaConverter.Value(GraphQLValue source)
   at GraphQL.Language.CoreToVanillaConverter.ObjectField(GraphQLObjectField source)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema)
   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema)
   at GraphQL.Validation.Rules.ArgumentsOfCorrectType.<>c__DisplayClass1_0.<ValidateAsync>b__1(Argument argAst)
   at GraphQL.Validation.MatchingNodeVisitor`1.GraphQL.Validation.INodeVisitor.Enter(INode node)
   at GraphQL.Validation.EnterLeaveListener.GraphQL.Validation.INodeVisitor.Enter(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.DocumentValidator.ValidateAsync(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules, IDictionary`2 userContext, Inputs inputs)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
```

### Steps to reproduce

Here is a basic console application example:
```
        static async Task Main(string[] args)
        {
            var schema = FederatedSchema.For($@"
              extend type Query {{
                hello(helloInput: HelloInput!): String
              }}

                input HelloNestedInput {{
                    testNestedString: String
                }}

                input HelloInput {{
                    testString: String
                    testArray: [String!]
                }}

            type User @key(fields: ""id"") {{
                id: ID!
            }}
            ", builder =>
            {
                builder.Types.For("User").ResolveReferenceAsync(context =>
                {
                    var id = (string) context.Arguments["id"];

                    return Task.FromResult(new {id});
                });
            });

            var json = await schema.ExecuteAsync(new DocumentWriter(),_ =>
            {
                _.Query = @"{ hello(helloInput: {testString: ""test"", testArray: []})  }";
                _.Root = new {Hello = "Hello World!"};
            });

            Console.WriteLine(json);
        }
```

### Expected result

The empty array should be valid, and should deserialize successfully. 

### Actual result

The above exception was thrown.

### Environment

```
    <TargetFramework>netcoreapp3.1</TargetFramework>
```

```
    <PackageReference Include="GraphQL" Version="3.0.0-preview-1490" />
    <PackageReference Include="GraphQL-Parser" Version="5.1.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1490" />
```

**Comment by sungam3r** [comment]
Many thanks for test example. Fixed.

**Comment by bgoerdt** [comment]
> Thanks a lot for the test case.

No problem! Thanks for the quick fix!
