### ISSUE TITLE
Schemas containing type or field description fail to be parsed correctly

### ISSUE THREAD

**Issue by almazik** [graphql-dotnet/graphql-dotnet#1640]
## Description

The attempt to parse schema with description tokens results in exception

### Steps to reproduce

```
var schema = Schema.For(@"""Root type for all queries""
type Query {
  name: String
}");
```

### Expected result

Documentation should either be ignored or parsed into the corresponding fields

### Actual result

Exception

```
GraphQLParser.Exceptions.GraphQLSyntaxErrorException: Syntax Error GraphQL (1:1) Unexpected String "Root type for all queries"
1: "Root type for all queries"
   ^
2: type Query {

  at at GraphQLParser.ParserContext.ParseDefinition()
  at at GraphQLParser.ParserContext.ParseDefinitionsIfNotEOF()
  at at GraphQLParser.ParserContext.ParseDocument()
  at at GraphQLParser.ParserContext.Parse()
  at at GraphQLParser.Parser.Parse(ISource source)
  at at GraphQL.Utilities.SchemaBuilder.Parse(String document)
  at at GraphQL.Utilities.SchemaBuilder.Build(String typeDefinitions)
  at at GraphQL.Types.Schema.For(String typeDefinitions, Action`1 configure)
```

### Environment

.NET Core 3.1, graphql-dotnet 3.0.0-preview-1490

**Comment by sungam3r** [comment]
1. Relates to https://github.com/graphql-dotnet/parser/issues/33
2. Did you intentionally use duplicate double quotes? http://spec.graphql.org/June2018/#sec-Descriptions talks about `"""` for block descriptions and `"` for single line descriptions.

**Comment by almazik** [comment]
1. yes, agree, noticed parser issue once I started digging into the source code.
2. duplicate quotes here are just C# escape symbols for verbatim strings (@"..."), the resulting string constant is 

> "Root type for all queries"
> type Query {
>   "Documentation for the field"
>   name: String
> }

**Comment by sungam3r** [comment]
I can confirm this bug. Transferring issue into parser repo.
