### ISSUE TITLE
How to Extend Interface Type with Federation

### ISSUE THREAD

**Issue by itabaiyu** [graphql-dotnet/graphql-dotnet#1731]
## Summary

I'm looking for examples about how to extend an interface rather than a concrete type while working with Apollo federation.

## Relevant information

 I'm attempting to do this with the following code, with AutoFac:

```cs
builder.Register(componentContext =>
    {
        var resolver = componentContext.Resolve<IFederatedResolver>();

        return FederatedSchema.For(@"
            extend interface Product_Interface @key(fields: ""sku"") {
                sku: String @external,
                name: String
            }

            type Query {
                product(sku: String!): Product_Interface!
            }",
            _ =>
            {
                _.ServiceProvider = componentContext.Resolve<IServiceProvider>();
                _.Types.Include<Query>();
                _.Types.For("Product_Interface").ResolveReferenceAsync(resolver);
            }
        );
    }
).As<ISchema>().InstancePerDependency();
```

This results in the following error on load of the GraphQL playground: 

```cs
{
  "error": "Unexpected token A in JSON at position 0"
}
```

And internally this exception is being thrown:

```cs
Autofac.Core.DependencyResolutionException: An exception was thrown while activating λ:GraphQL.Types.ISchema.
 ---> GraphQLParser.Exceptions.GraphQLSyntaxErrorException: Syntax Error GraphQL (26:20) Expected "type", found Name "interface"
25: 
26:             extend interface Product_Interface @key(fields: "sku") {
                       ^
27:                 sku: String @external,

   at GraphQLParser.ParserContext.ExpectKeyword(String keyword)
   at GraphQLParser.ParserContext.ParseObjectTypeDefinition()
   at GraphQLParser.ParserContext.ParseTypeExtensionDefinition()
   at GraphQLParser.ParserContext.ParseNamedDefinition()
   at GraphQLParser.ParserContext.ParseDefinition()
   at GraphQLParser.ParserContext.ParseDefinitionsIfNotEOF()
   at GraphQLParser.ParserContext.ParseDocument()
   at GraphQLParser.ParserContext.Parse()
   at GraphQLParser.Parser.Parse(ISource source)
   at GraphQL.Utilities.SchemaBuilder.Parse(String document) in C:\projects\graphql-dotnet\src\GraphQL\Utilities\SchemaBuilder.cs:line 78
   at GraphQL.Utilities.SchemaBuilder.Build(String typeDefinitions) in C:\projects\graphql-dotnet\src\GraphQL\Utilities\SchemaBuilder.cs:line 58
   at GraphQL.Utilities.Federation.FederatedSchemaBuilder.Build(String typeDefinitions) in C:\projects\graphql-dotnet\src\GraphQL\Utilities\Federation\FederatedSchemaBuilder.cs:line 45
   at GraphQL.Utilities.Federation.FederatedSchema.For(String typeDefinitions, Action`1 configure) in C:\projects\graphql-dotnet\src\GraphQL\Utilities\Federation\FederatedSchema.cs:line 18
```

Is extending interfaces supported with Federation? If they are, how would one go about doing that correctly?

### Environment (if relevant)

Package versions:

```
<PackageReference Include="GraphQL" Version="3.0.0-preview-1648" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.Server.Ui.Voyager" Version="3.5.0-alpha0046" />
<PackageReference Include="GraphQL.SystemTextJson" Version="3.0.0-preview-1648" />
```

**Comment by itabaiyu** [comment]
I was able to get the parser working by using the following schema:

```
builder.Register(componentContext =>
    {
        var resolver = componentContext.Resolve<IFederatedResolver>();

        return FederatedSchema.For(@"
            interface Product_Interface @extends {
                name: String
            }

            extend type Product implements Product_Interface @key(fields: ""sku"") {
                sku: String @external
                name: String
            }

            type Query {
                product(sku: String!): Product_Interface 
            }",
            _ =>
            {
                _.ServiceProvider = componentContext.Resolve<IServiceProvider>();
                _.Types.Include<Query>();
                _.Types.For("Product_Interface").ResolveReferenceAsync(resolver);
            }
        );
    }
).As<ISchema>().InstancePerDependency();
```

But on page load for the playground we began seeing the following error and the schema fails to be loaded into the playground  UI:

```
{"Interface type Product_Interface does not provide a \"resolveType\" function and possible Type \"Product\" does not provide a \"isTypeOf\" function.  There is no way to resolve this possible type during execution."}
```

I'm not familiar with `resolveType` but I added this to where we configure our schema:

```csharp
_.Types.For("Product_Interface_Type").ResolveType = obj => new GraphQLTypeReference(typeof(Product).Name);
```

☝️ this allows for the schema to be correctly built and show in the playground, but on querying the graph we get a `Error trying to resolve _entities.` error, with the following stack trace:

```
Object reference not set to an instance of an object.
at GraphQL.Language.AST.SelectionSet.Merge(SelectionSet otherSelection) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Language\\AST\\SelectionSet.cs:line 39
at GraphQL.Language.AST.Field.MergeSelectionSet(Field other) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Language\\AST\\Field.cs:line 75
at GraphQL.Language.AST.Fields.Add(Field field) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Language\\AST\\Fields.cs:line 29
at GraphQL.Execution.ExecutionHelper.CollectFields(ExecutionContext context, IGraphType specificType, SelectionSet selectionSet, Fields fields, List`1 visitedFragmentNames) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionHelper.cs:line 326
at GraphQL.Execution.ExecutionHelper.CollectFields(ExecutionContext context, IGraphType specificType, SelectionSet selectionSet, Fields fields, List`1 visitedFragmentNames) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionHelper.cs:line 350
at GraphQL.Execution.ExecutionHelper.CollectFields(ExecutionContext context, IGraphType specificType, SelectionSet selectionSet) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionHelper.cs:line 371
at GraphQL.Execution.ExecutionStrategy.SetSubFieldNodes(ExecutionContext context, ObjectExecutionNode parent) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionStrategy.cs:line 56
at GraphQL.Execution.ExecutionStrategy.SetArrayItemNodes(ExecutionContext context, ArrayExecutionNode parent) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionStrategy.cs:line 116
at GraphQL.Execution.ExecutionStrategy.<ExecuteNodeAsync>d__7.MoveNext() in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\ExecutionStrategy.cs:line 238
```

I feel like I am close, but something is still missing. An example of how to do this would be incredibly helpful. 🙏

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/docs2/site/docs/getting-started/interfaces.md

**Comment by itabaiyu** [comment]
@sungam3r thanks for the docs link. Unfortunately that doesn't appear to have documentation about how to do this when following the schema-first pattern and only shows examples for the graph-type-first approach. Could you provide an example of how `resolveType` could be implemented given the code I shared in https://github.com/graphql-dotnet/graphql-dotnet/issues/1731#issuecomment-664655960?
