### ISSUE TITLE
Schema printer doesn't support lists as default objects. 

### ISSUE THREAD

**Issue by oconnor0** [graphql-dotnet/graphql-dotnet#1759]
### Steps to reproduce

Create a new dotnet project and put this code in the Program.cs:

```
namespace Alphabet
{
    class Program
    {
        static void Main(string[] args)
        {
            var schema = GraphQL.Types.Schema.For(@"
enum Alphabet {
  A
  B
  C
}

type Subscription {
  alphabets(letters: [Alphabet!] = [A, B]): [String!]
}
            ");


            var options = new GraphQL.Utilities.SchemaPrinterOptions {
                IncludeDescriptions = true,
                IncludeDeprecationReasons = true,
            };

            var printer = new GraphQL.Utilities.SchemaPrinter(schema, options);
            System.Console.WriteLine(printer.Print());
        }
    }
}
```

As far as I know, this is using the [GraphQL.NET from master, commit hash 6d2667c9ecd854a3fee4e24019a2e68b7d4b37de](https://github.com/graphql-dotnet/graphql-dotnet/tree/6d2667c9ecd854a3fee4e24019a2e68b7d4b37de)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\graphql-dotnet\src\GraphQL\GraphQL.csproj" />
    <ProjectReference Include="..\..\..\graphql-dotnet\src\GraphQL.NewtonsoftJson\GraphQL.NewtonsoftJson.csproj" />
  </ItemGroup>

</Project>
```

### Expected result

The schema displays without error.

### Actual result

```
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'GraphQL.Types.ListGraphType' to type 'GraphQL.Types.EnumerationGraphType'.
   at GraphQL.Utilities.SchemaPrinter.SerializeEnumValue(IGraphType type, Object value) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 322
   at GraphQL.Utilities.SchemaPrinter.FormatDefaultValue(Object value, IGraphType graphType) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 294
   at GraphQL.Utilities.SchemaPrinter.PrintInputValue(QueryArgument argument) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 257
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at GraphQL.Utilities.SchemaPrinter.PrintArgs(FieldType field) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 234
   at GraphQL.Utilities.SchemaPrinter.<PrintFields>b__25_0(FieldType x) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 214
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GraphQL.Utilities.SchemaPrinter.PrintFields(IComplexGraphType type) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 212
   at GraphQL.Utilities.SchemaPrinter.PrintObject(IObjectGraphType type) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 184
   at GraphQL.Utilities.SchemaPrinter.PrintType(IGraphType type) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 161
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GraphQL.Utilities.SchemaPrinter.PrintFilteredSchema(Func`2 directiveFilter, Func`2 typeFilter) in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 64
   at GraphQL.Utilities.SchemaPrinter.Print() in C:\src\graphql-dotnet\src\GraphQL\Utilities\SchemaPrinter.cs:line 43
   at Alphabet.Program.Main(String[] args) in C:\src\personal\graphql\Err\Program.cs:line 26
```

### Environment

Windows 10
dotnet 3.1
GraphQL master 6d2667c9ecd854a3fee4e24019a2e68b7d4b37de

**Comment by sungam3r** [comment]
Thanks for reporting this.

**Comment by sungam3r** [comment]
@oconnor0 merged 👍
