### ISSUE TITLE
System.NullReferenceException with UnionGraphType

### ISSUE THREAD

**Issue by inputfalken** [graphql-dotnet/graphql-dotnet#1883]
## Description

I'm experiencing runtime exceptions occasionally when we get requests due to null values in PossibleTypes for `UnionGraphType`.

![image](https://user-images.githubusercontent.com/14941509/94541896-6debc180-0248-11eb-9f1d-aa2ee4e728d5.png)

The `GraphType` I'm experiencing problems with: 
```csharp
public class TagLookupGraphType : UnionGraphType 
{
    public TagLookupGraphType()
    {
        Type<TagGraphType>();
        Type<TagNotFoundGraphType>();
    }
}
```

### Steps to reproduce

This does not happen regularly and I'm not sure what's causing it.

### Expected result

There should be no errors. 😉

### Actual result

```
GraphQL.Execution.UnhandledError: Error executing document.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 287
   at GraphQL.Types.GraphTypesLookup.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 332
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 248
   at GraphQL.Types.GraphTypesLookup.AddTypeWithLoopCheck(IGraphType resolvedType, TypeCollectionContext context, Type namedType) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 385
   at GraphQL.Types.GraphTypesLookup.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 332
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 248
   at GraphQL.Types.GraphTypesLookup.AddTypeWithLoopCheck(IGraphType resolvedType, TypeCollectionContext context, Type namedType) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 385
   at GraphQL.Types.GraphTypesLookup.HandleField(IComplexGraphType parentType, FieldType field, TypeCollectionContext context, Boolean applyNameConverter) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 332
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 248
   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, INameConverter nameConverter, Boolean seal) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\GraphTypesLookup.cs:line 90
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at GraphQL.Types.Schema.FindType(String name) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\Schema.cs:line 228
   at GraphQL.Types.Schema.Initialize() in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Types\\Schema.cs:line 78
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options) in C:\\projects\\graphql-dotnet\\src\\GraphQL\\Execution\\DocumentExecuter.cs:line 66
   --- End of inner exception stack trace ---",
    "SourceContext": "Domain.Api.GraphQl.GraphQlResponseBuilder
```

### Environment

* GraphQL Version:  3.0.0.2026

This happens both on Linux Docker containers and our local windows environments.

**Comment by Shane32** [comment]
Is your schema registered as a singleton?  If so, `Schema.Initialize()` should not occur more than once during the application's lifetime.  Does only happen at startup?  Do you use middleware?

**Comment by brunoblank** [comment]
The schema is registered as a **ScopedType**.
This error happens on every request once the error has been triggered.
The execution of the graphql request is done through a Controller.

Some background. 
We are in the middle of migrating our graph types from using constructor injection **=>** retrieve dependencies through the `context.RequestServices` in the Resolve method. 
So new migrated GraphTypes are registered as SingleInstance. However, the schema and query-root will have to wait until all downstream types are migrated until everything can be single-instance.

**Comment by Shane32** [comment]
That explains it. You can’t have singleton graph types with a scoped schema. 

See https://graphql-dotnet.github.io/docs/getting-started/dependency-injection :

> With scoped schemas, it is **required** that all its graph types are registered within the DI framework as scoped or transient services.

**Comment by Shane32** [comment]
This is because initialization of the schema initializes the ResolvedType properties of the graph types and field types. It also updates the resolver functions if middleware is applied. Since you have a scoped schema, initialization is finding graph types with the ResolvedType property already set when it should not be. Other concurrency issues and memory leaks can occur as well, as a ResolvedType property may be set to an unused/disposed instance of other graph types.

**Comment by brunoblank** [comment]
Ah, that explains it.

We will switch back to scoped, until everything has been migrated and then make the change for single instance.

Thanks for clarifying!

**Comment by inputfalken** [comment]
Thanks for the help!👍 I will be closing the issue now.

**Comment by sungam3r** [comment]
To be honest, schema initialization is the kind of thing I'd redo. It is not thread safe and can lead to side effects due to race conditions.

**Comment by Shane32** [comment]
> To be honest, schema initialization is the kind of thing I'd redo. It is not thread safe and can lead to side effects due to race conditions.

I agree
