### ISSUE TITLE
Required service for type not found

### ISSUE THREAD

**Issue by zulander1** [graphql-dotnet/graphql-dotnet#2135]
I have having the same issue as [this](https://github.com/graphql-dotnet/graphql-dotnet/issues/1363), spent a lot of time figuring it out with no luck, I am using .net5

the error is: Required service for type EmployeeQuery not found' located in EmployeeSchema 

Stack
   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 42
   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 18
   at EmployeeServices.EmployeeSchema..ctor(IServiceProvider serviceProvider) in C:\Users\source\\EmployeeServices\Class.cs:line 16

**EmployeeSchema** 
```

    public class EmployeeSchema : Schema
    {
        public EmployeeSchema(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<EmployeeQuery>();
            RegisterType<EmployeeType>();
        }
    }

```
**AddApplicationGraphQL**
```

        public static IGraphQLBuilder AddApplicationGraphQL(this IServiceCollection services)
        {
            return services
                 .AddSingleton<EmployeeSchema>()
                .AddGraphQL((options, provider) =>
                {
                    options.EnableMetrics = true;
                    var logger = provider.GetRequiredService<ILogger<Startup>>();
                    options.UnhandledExceptionDelegate = ctx => logger.LogError("{Error} occured", ctx.OriginalException.Message);
                })
                .AddSystemTextJson(deserializerSettings => { }, serializerSettings => { })
                .AddGraphTypes(typeof(EmployeeSchema));
        }
    }
```

**EmployeeSchema** 

```
    public class EmployeeSchema : Schema
    {
        public EmployeeSchema(IServiceProvider serviceProvider) : base(serviceProvider)
        {
            Query = serviceProvider.GetRequiredService<EmployeeQuery>();
            RegisterType<EmployeeType>();
        }
    }
```
**Startup**

```

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddDbContext<ManagerContext>(options => options.UseSqlServer(Configuration.GetConnectionString("test")));

            services.AddScoped<IEmployeeRepository, EmployeeRepository>();
            services.AddMemoryCache();
            services.AddApplicationGraphQL();
 
            services.AddControllers();
        }

     public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseRouting();
  
            app.UseGraphQL<EmployeeSchema>();
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }

```
 **EmployeeType** 

```
    public class EmployeeType : ObjectGraphType<EmployeeModel>
    {
        public EmployeeType()
        {
            Name = "Employee";
            Description = "List of active Employees";
            Field(d => d.Id, nullable: false).Description("Employee Id");
           ...
        }
    }

```
**EmployeeQuery**

```
    public class EmployeeQuery : ObjectGraphType
    {
        public EmployeeQuery()
        {
            FieldAsync<ListGraphType<EmployeeType>>(
                "employees",
                resolve: async context =>
                {
                    return await context.RequestServices.GetRequiredService<IEmployeeRepository>().GetActiveEmployeesAsync();
                });
        }
    }
```

EDIT:

```
<ItemGroup>
		<PackageReference Include="GraphQL" Version="3.2.0" />
		<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="4.4.0" />
		<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="4.4.0" />
		<PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="4.4.0" />
		<PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.4.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="5.0.1" NoWarn="NU1605" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.1" NoWarn="NU1605" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.1" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="5.6.3" />
	</ItemGroup>
```

**Comment by sungam3r** [comment]
Whar version of GraphQL.NET / server packages do you use? Also show exception stack trace.

**Comment by zulander1** [comment]
I`ve updated the issue

**Comment by zulander1** [comment]
did a quick test with serviceProvider.GetService(typeof(EmployeeQuery)) getting null

**Comment by sungam3r** [comment]
`.AddGraphTypes(typeof(EmployeeSchema));` adds all discovered graph types from assembly where `EmployeeSchema` resides. The error clearly indicates that there is no `EmployeeQuery` in your list of services.

**Comment by zulander1** [comment]
You mean using IDependencyResolver ?

**Comment by sungam3r** [comment]
What?

**Comment by zulander1** [comment]
Never mind... I have figured it out Thank you so much !!!!
