### ISSUE TITLE
GraphQL.Execution.UnhandledError

### ISSUE THREAD

**Issue by armaniehs** [graphql-dotnet/graphql-dotnet#2292]
I mistakenly defined a string field (name) as decimal in my input type

```csharp    
public partial class DepartmentInputType : InputObjectGraphType
    {
        public DepartmentInputType()
        {
            Name = "DepartmentInput";
            Field<GuidGraphType>("uuid");
            Field<StringGraphType>("code");
            Field<NonNullGraphType<DecimalGraphType>>("name");
            Field<StringGraphType>("description");
            Field<StringGraphType>("comments");
        }
    }
```
and got the following error when setting *name* with a string value

```json
{
  "errors": [
    {
      "message": "GraphQL.Execution.UnhandledError: Error executing document.\r\n ---> System.FormatException: Input string was not in a correct format.\r\n   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)\r\n   at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)\r\n   at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)\r\n   at GraphQL.ValueConverter.<>c.<.cctor>b__1_11(String value) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 39\r\n   at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 224\r\n   at GraphQL.ValueConverter.TryConvertTo(Object value, Type targetType, Object& result, Type sourceType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 184\r\n   at GraphQL.ValueConverter.ConvertTo(Object value, Type targetType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 158\r\n   at GraphQL.Types.DecimalGraphType.ParseValue(Object value) in /_/src/GraphQL/Types/Scalars/DecimalGraphType.cs:line 25\r\n   at GraphQL.Types.DecimalGraphType.ParseLiteral(IValue value) in /_/src/GraphQL/Types/Scalars/DecimalGraphType.cs:line 16\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 283\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 213\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema)\r\n   at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 213\r\n   at GraphQL.Validation.Rules.ArgumentsOfCorrectType.<>c__DisplayClass1_0.<ValidateAsync>b__1(Argument argAst) in /_/src/GraphQL/Validation/Rules/ArgumentsOfCorrectType.cs:line 33\r\n   at GraphQL.Validation.EnterLeaveListener.GraphQL.Validation.INodeVisitor.Enter(INode node) in /_/src/GraphQL/Validation/EnterLeaveListener.cs:line 34\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 41\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 55\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 55\r\n   at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50\r\n   at GraphQL.Validation.MyDocumentValidator.ValidateAsync(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules, IDictionary`2 userContext, Inputs inputs) in C:\\code\\dev\\live\\Meercat.RiskView\\Ehs.Risk.GraphQL\\MyDocumentValidator.cs:line 84\r\n   at Ehs.Risk.GraphQL.MyDocumentExecuter.ExecuteAsync(ExecutionOptions options) in C:\\code\\dev\\live\\Meercat.RiskView\\Ehs.Risk.GraphQL\\MyDocumentExecuter.cs:line 111\r\n   --- End of inner exception stack trace ---",
      "extensions": {
        "code": "FORMAT",
        "codes": [
          "FORMAT"
        ]
      }
    }
  ],
  "extensions": {
    "tracing": {
      "version": 1,
      "startTime": "2021-02-16T19:22:48.6791269Z",
      "endTime": "2021-02-16T19:22:50.5831269Z",
      "duration": 1903948599,
      "parsing": {
        "startOffset": 4200,
        "duration": 32599
      },
      "validation": {
        "startOffset": 38600,
        "duration": 1903875299
      },
      "execution": {
        "resolvers": []
      }
    }
  }
}
```

The error message doesn't mention which field is getting parsed.

After several minutes I managed to figure out which field wasn't correctly defined by debugging GraphQL.NET source code.

Wouldn't it be possible to add the field name to the error message?

Cheers,

Sil

**Comment by Shane32** [comment]
Was the value passed as a literal or a variable ?

**Comment by sungam3r** [comment]
Formatted StackTrace:
```
"message": "GraphQL.Execution.UnhandledError: Error executing document.
 System.FormatException: Input string was not in a correct format.
 at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
 at System.Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
 at System.Decimal.Parse(String s, NumberStyles style, IFormatProvider provider)
 at GraphQL.ValueConverter.<>c.<.cctor>b__1_11(String value) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 39
 at GraphQL.ValueConverter.<>c__DisplayClass7_0`2.<Register>b__0(Object v) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 224
 at GraphQL.ValueConverter.TryConvertTo(Object value, Type targetType, Object& result, Type sourceType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 184
 at GraphQL.ValueConverter.ConvertTo(Object value, Type targetType) in /_/src/GraphQL/Conversion/ValueConverter.cs:line 158
 at GraphQL.Types.DecimalGraphType.ParseValue(Object value) in /_/src/GraphQL/Types/Scalars/DecimalGraphType.cs:line 25 
 at GraphQL.Types.DecimalGraphType.ParseLiteral(IValue value) in /_/src/GraphQL/Types/Scalars/DecimalGraphType.cs:line 16
 at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 283
 at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 213
 at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema)  
 at GraphQL.GraphQLExtensions.IsValidLiteralValue(IGraphType type, IValue valueAst, ISchema schema) in /_/src/GraphQL/GraphQLExtensions.cs:line 213
 at GraphQL.Validation.Rules.ArgumentsOfCorrectType.<>c__DisplayClass1_0.<ValidateAsync>b__1(Argument argAst) in /_/src/GraphQL/Validation/Rules/ArgumentsOfCorrectType.cs:line 33
 at GraphQL.Validation.EnterLeaveListener.GraphQL.Validation.INodeVisitor.Enter(INode node) in /_/src/GraphQL/Validation/EnterLeaveListener.cs:line 34
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 41
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 55
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 55
 at GraphQL.Validation.BasicVisitor.Visit(INode node) in /_/src/GraphQL/Validation/BasicVisitor.cs:line 50
 at GraphQL.Validation.MyDocumentValidator.ValidateAsync(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules, IDictionary`2 userContext, Inputs inputs) in C:\\code\\dev\\live\\Meercat.RiskView\\Ehs.Risk.GraphQL\\MyDocumentValidator.cs:line 84
 at Ehs.Risk.GraphQL.MyDocumentExecuter.ExecuteAsync(ExecutionOptions options) in C:\\code\\dev\\live\\Meercat.RiskView\\Ehs.Risk.GraphQL\\MyDocumentExecuter.cs:line 111 
 --- End of inner exception stack trace ---
```

**Comment by sungam3r** [comment]
See `mutation_input_from_variables`. It yields 
```json
    {
      "errors": [
        {
          "message": "Variable \u0027$userInput.profileImage\u0027 is invalid. Unable to convert \u0027myimage.png\u0027 to \u0027Decimal\u0027",
          "locations": [
            {
              "line": 2,
              "column": 37
            }
          ],
          "extensions": {
            "code": "INVALID_VALUE",
            "codes": [
              "INVALID_VALUE",
              "FORMAT"
            ],
            "number": "5.8"
          }
        }
      ]
    }
```

**Comment by sungam3r** [comment]
Changed to literal :
```json
 {
      "errors": [
        {
          "message": "Error executing document.",
          "extensions": {
            "code": "FORMAT",
            "codes": [
              "FORMAT"
            ]
          }
        }
      ]
    }
```

**Comment by sungam3r** [comment]
After fix:
```json
 {
      "errors": [
        {
          "message": "Argument \u0022userInput\u0022 has invalid value {profileImage: \u0022myimage.png\u0022, gender: Female}.\nIn field \u0022profileImage\u0022: Expected type \u0022Decimal\u0022, found \u0022myimage.png\u0022.",
          "locations": [
            {
              "line": 3,
              "column": 30
            }
          ],
          "extensions": {
            "code": "ARGUMENTS_OF_CORRECT_TYPE",
            "codes": [
              "ARGUMENTS_OF_CORRECT_TYPE"
            ],
            "number": "5.6.1"
          }
        }
      ]
    }
```

**Comment by sungam3r** [comment]
Fixed.
