### ISSUE TITLE
NullReferenceException when passing argument to field that has no arguments

### ISSUE THREAD

**Issue by siada** [graphql-dotnet/graphql-dotnet#232]
I'm pretty new with using GraphQL so bear with me if I've completed misunderstood this....

I'm executing a schema against a complex object to return the properties specified in the schema, and this all works great! What I'm trying to achieve now is filter an array property down to only it's first element, if I use this schema: 

```graphql
query {
    Objects {
      Images {
        Url
      }
    }
}

```
It works, but returns all the Url properties for every occurrence of an Image, however if I do this:
```graphql
 query {
    Objects {
      Images(first: 1) {
        Url
      }
    }
  }
```

I get the following exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GraphQL.Validation.Rules.KnownArgumentNames.<>c__DisplayClass2_0.<Validate>b__1(Argument node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.Validation.BasicVisitor.Visit(INode node)
   at GraphQL.Validation.DocumentValidator.Validate(String originalQuery, ISchema schema, Document document, IEnumerable`1 rules)
   at GraphQL.DocumentExecuter.<ExecuteAsync>d__4.MoveNext()
```

And here is a sample of my data from the schema that works:
```json
{
  "Objects": [
    {
      "Images": [
        {
          "Url": "http://example.com/1.jpg"
        },
        {
          "Url": "http://example.com/2.jpg"
        },
        {
          "Url": "http://example.com/3.jpg"
        },
        {
          "Url": "http://example.com/4.jpg"
        }
      ]
    }
  ]
}
```
but I'd like to see:
```json
{
  "Objects": [
    {
      "Images": [
        {
          "Url": "http://example.com/1.jpg"
        }
      ]
    }
  ]
}
```

**Comment by joemcbride** [comment]
Can you add your code for your GraphType?  One issue may be - PascalCase is currently not supported, all fields must be camelCase.

**Comment by siada** [comment]
Is the `first` option not built in? Does it have to be part of my GraphType? I don't actually manually construct any of my Graph objects, I use the attachment from https://github.com/graphql-dotnet/graphql-dotnet/issues/196 to generate them, could this be causing my isssue?

**Comment by joemcbride** [comment]
There are no built-in arguments in the core project so `first` would not exist there.  There does appear to be a bug here since you shouldn't be getting a null reference exception, though the issue probably is that `first` doesn't exist.

**Comment by joemcbride** [comment]
If you can post some sample code that reproduces the null reference that would be appreciated.

**Comment by joemcbride** [comment]
Hah, looks like I was able to reproduce this null reference so I'll get that fixed.

**Comment by siada** [comment]
Okay glad we found that out haha, could you point me in the right direction with how to achieve what I'm trying? I've read through the official GraphQL docs and it does mention about parameters like first, last, skip etc. I'm just trying to get the first element of an array.

**Comment by joemcbride** [comment]
I'm just making this example up, though you would need to add those Arguments to the field definition of `images`.  This is using the core project of course and not that wrapper.

```csharp
public class ImagesQuery : ObjectGraphType
{
  public ImagesQuery(IImagesLoader loader)
  {
    Field<ListGraphType<ImageGraphType>>(
      "images",
      arguments: new QueryArguments(new QueryArgument<IntGraphType> { Name = "first" }),
      resolve: context =>
      {
        var first = context.GetArgument<int>("first");
        return loader.LoadImages().Take(first);
      }
    );
  }
}
```

**Comment by joemcbride** [comment]
That first, last, skip seems to be related to paging.  There is nothing built-in to the GraphQL spec about how that is implemented.  Those are fairly closely related to Relay though.  So if you're planning on perhaps using Relay, you can look at the Relay types provided in the core project and these addtional ones: https://github.com/graphql-dotnet/relay
