### ISSUE TITLE
Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime after upgrading to version 4

### ISSUE THREAD

**Issue by markmcgookin** [graphql-dotnet/graphql-dotnet#2471]
Our application was working fine, I have updated to the latest version of all GQL dependencies in our net5.0 web app and the application fails to start with the below error.

### Expected result

Application should start up.

### Actual result

Exception thrown at runtime when trying to start up after upgrading all GQL dependencies to latest version:

```
<PackageReference Include="GraphQL" Version="4.2.0" />
<PackageReference Include="GraphQL.SystemTextJson" Version="4.2.0" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="4.4.1" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.0.1" />
<PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="5.0.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="4.2.0" />
```
Exception: 
```

Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime: Transient ImplementationType: GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule': Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: GraphQL.Validation.IValidationRule Lifetime: Transient ImplementationType: GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule': Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor' while attempting to activate 'GraphQL.Server.Authorization.AspNetCore.AuthorizationValidationRule'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MyProject.Program.Main(String[] args) in work/MyProject/GraphQL/Program.cs:line 13
```

**Comment by Shane32** [comment]
Looks like what might be key here is:
```
Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor
```

**Comment by markmcgookin** [comment]
> Looks like what might be key here is:
> 
> ```
> Unable to resolve service for type 'GraphQL.Server.Authorization.AspNetCore.IClaimsPrincipalAccessor
> ```

Is this something new that I need to add in? The docs for moving from 3.X to 4.X said no calling code changes were needed re:authorization

**Comment by Shane32** [comment]
I’m not sure. I have not worked with that repo. @sungam3r might know.
