### ISSUE TITLE
Cannot instantiate implementation type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer' for service type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer'.

### ISSUE THREAD

**Issue by ASkvorcov** [graphql-dotnet/graphql-dotnet#2554]
Hi,
Let me start by saying that I have read the README.md and [this issue](https://github.com/graphql-dotnet/server/issues/354)
Then i put this
`<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.0.2" />`
and this
`services.AddGraphQL(options =>
			{
				options.EnableMetrics = true;
			}).AddSystemTextJson();`
in my code

but anyway i got an error

`System.ArgumentException
  HResult=0x80070057
  Сообщение = Cannot instantiate implementation type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer' for service type 'GraphQL.Server.Transports.AspNetCore.IGraphQLRequestDeserializer'.
  Источник = Microsoft.Extensions.DependencyInjection
  Трассировка стека:
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MlgBuzz.BlogRating.Api.Program.Main(String[] args)`

This is the packaged in the project. I am using netcoreapp3.1.
`<ItemGroup>
		<PackageReference Include="GraphQL.NewtonsoftJson" Version="4.5.0" />
		<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.0.2" />
		<PackageReference Include="linq2db.EntityFrameworkCore" Version="3.5.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.1.9" />
		<PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="3.1.9" />
		<PackageReference Include="GraphQL" Version="4.5.0" />
		<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.0.2" />
		<PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.0.2" />
		<PackageReference Include="Microsoft.OpenApi" Version="1.2.3" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="3.1.0" />
    <PackageReference Include="NEST" Version="7.12.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="4.2.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="3.3.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		
	</ItemGroup>`

This is my Startup
`public class Startup
	{
		private readonly IConfiguration Configuration;

		public Startup(IConfiguration configuration)
		{
			Configuration = configuration;
		}

		public void ConfigureServices(IServiceCollection services)
		{
			services.AddDbContext<BlogRatingDbContext>(opts => opts
				.UseSqlServer(Configuration.GetConnectionString("BlogRatings")),
				ServiceLifetime.Transient);

			RegisterServices(services);
			RegisterConfigs(services);
			RegisterGraphQLTypes(services);

			services.AddApiVersioning(o =>
			{
				o.ReportApiVersions = true;
				o.ApiVersionReader = ApiVersionReader.Combine(
					new HeaderApiVersionReader(Consts.ApiVersionHeader),
					new QueryStringApiVersionReader());
			});

			services.AddSwaggerGen(c =>
			{
				c.SwaggerDoc("v1", new OpenApiInfo {
					Title = GetType().Namespace,
					Version = "v1"
				});

				// Set the comments path for the Swagger JSON and UI.
				var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
				var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
				c.IncludeXmlComments(xmlPath);
				c.OperationFilter<SwaggerDefaultValuesFilter>();
				c.DocumentFilter<SwaggerRootPathFilter>();
			});

			services.AddControllers();

			services.AddGraphQL(options =>
			{
				options.EnableMetrics = true;
			}).AddSystemTextJson();
		}

		private void RegisterConfigs(IServiceCollection services)
		{
			services.Configure<SwaggerConfig>(Configuration);
			services.Configure<DataBaseConfig>(Configuration);
			services.Configure<BlogElasticConfig>(Configuration);
		}

		private void RegisterServices(IServiceCollection services)
		{
			services.AddCors();
			services.AddHostedService<BlogRatingDbInitializer>();
			services.AddStandardTracing(Configuration);
			services.AddLog4NetComplexDataLogger();
			services.AddTransient<IServiceProvider>(s => new FuncServiceProvider(s.GetRequiredService));
			services.AddTransient<ISchema, ApiSchema>();
			services.AddTransient<IBlogRatingService, BlogRatingService>();
			services.AddTransient<IIntervalService, IntervalService>();
			services.AddTransient<ITopicService, TopicService>();
			services.AddTransient<IHostService, HostService>();
			services.AddSingleton<IBlogAccessor, BlogAccessor>();
			services.AddTransient<IBlackAndWhiteListRepository, BlackAndWhiteListRepository>();
			services.AddTransient<IGraphQLRequestDeserializer>();
		}

		private void RegisterGraphQLTypes(IServiceCollection services)
		{
			services.AddScoped<ApiQuery>();

			services.AddScoped<BlogRatingResultType>();
			services.AddScoped<BlogRatingListResultsType>();
			services.AddScoped<BlogType>();
			services.AddScoped<BlogRatingQuery>();
			services.AddScoped<OrderByType>();
			services.AddScoped<OrderDirectionType>();

			services.AddScoped<IntervalType>();
			services.AddScoped<IntervalResultType>();
			services.AddScoped<IntervalListResultsType>();
			services.AddScoped<IntervalQuery>();

			services.AddScoped<TopicType>();
			services.AddScoped<TopicQuery>();
			services.AddScoped<TopicListResultsType>();

			services.AddScoped<HostType>();
			services.AddScoped<HostQuery>();
			services.AddScoped<HostListResultsType>();
		}

		public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
		{
			if (env.EnvironmentName == "Development")
			{
				app.UseDeveloperExceptionPage();
			}

			UseCors(app);

			app.UseSwagger();

			// Enable middleware to serve swagger-ui (HTML, JS, CSS, etc.),
			// specifying the Swagger JSON endpoint.
			app.UseSwaggerUI(c =>
			{
				c.SwaggerEndpoint("./swagger/v1/swagger.json", "mlgbuzz-blograting-api-v1");
				c.RoutePrefix = string.Empty;
			});

			app.UseRouting();
			app.UseEndpoints(builder =>
			{
				builder.MapControllers();
			});

			app.UseGraphQL<ISchema>("/");

			app.UseGraphQLPlayground(new PlaygroundOptions {
				GraphQLEndPoint = $"/ui/{Configuration.GetValue<string>("SWAGGER_BASE_PATH") ?? string.Empty}/"
			});
		}

		private void UseCors(IApplicationBuilder app)
		{
			var corsConfig = new CorsConfig();
			Configuration.Bind(corsConfig);
			app.UseCors(builder => builder
				.WithOrigins(corsConfig.ALLOWED_ORIGINS.Split(",", StringSplitOptions.RemoveEmptyEntries))
				.AllowAnyHeader().AllowAnyMethod());
		}
	}`

any solutions?

**Comment by Shane32** [comment]
Try removing:
```cs
services.AddTransient<IGraphQLRequestDeserializer>();
```

It is an invalid call, since you cannot register an interface without specifying a class to instantiate.

I would guess that the call to `.AddSystemTextJson()` will have you covered and you don't need the above line of code.  But if not, try adding something like this instead:

```cs
services.AddTransient<IGraphQLRequestDeserializer, GraphQLRequestDeserializer>();
```

I don't use the server project but @sungam3r can probably help if you're still having problems.  I'd probably review the sample projects to see if that registration is necessary or not.

I'm moving this to the server repo, where this question applies to.
