### ISSUE TITLE
Can't create at runtime any object that has a list property or a nun-nullable property

### ISSUE THREAD

**Issue by diaconesq** [graphql-dotnet/graphql-dotnet#257]
This was introduced by the fix to #241.
I can't create any complex type that contains a list-type or  non-nullable-type property.

The problem seems to occur due to the newly-added 'else' branch in `GraphTypesLookup.HandleField(...)`. 

See below test.

        [TestCase("none")] //passes
        [TestCase("list")]  //fails
        [TestCase("non-null")] //fails
        public void Test(string propType)
        {
            var nestedObjType = new ObjectGraphType()
            {
                Name = "NestedObjType"
            };
            nestedObjType.AddField(new FieldType()
            {
                ResolvedType = new IntGraphType(),
                Name = "intField"
            });
            var rootType = new ObjectGraphType {Name = "root"};
            IGraphType resolvedType;
            switch (propType)
            {
                case "none":
                {
                    resolvedType = nestedObjType;
                    break;
                }
                case "list":
                {
                    resolvedType = new ListGraphType(nestedObjType);
                    break;
                }
                case "non-null":
                {
                    resolvedType = new NonNullGraphType(nestedObjType);
                    break;
                }
                default:
                {
                    throw new NotSupportedException();
                }
            }

            rootType.AddField(new FieldType()
            {
                Name = "listOfObjField",
                ResolvedType = resolvedType
            });

            var s = new Schema()
            {
                Query = rootType
            };
            s.RegisterTypes(rootType, nestedObjType);
            new SchemaPrinter(s).Print();
        }

For failing tests, the error and trace are:

**GraphQL.ExecutionError : Only add root types.**

   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in GraphTypesLookup.cs: line 183
   at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(IGraphType type, TypeCollectionContext context) in GraphTypesLookup.cs: line 307
   at GraphQL.Types.GraphTypesLookup.HandleField(FieldType field, TypeCollectionContext context) in GraphTypesLookup.cs: line 275
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass14_0.<AddType>b__0(FieldType field) in GraphTypesLookup.cs: line 194
   at GraphQL.EnumerableExtensions.Apply(IEnumerable`1 items, Action`1 action) in EnumerableExtensions.cs: line 35
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context) in GraphTypesLookup.cs: line 192
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass3_0.<Create>b__1(IGraphType type) in GraphTypesLookup.cs: line 50
   at GraphQL.EnumerableExtensions.Apply(IEnumerable`1 items, Action`1 action) in EnumerableExtensions.cs: line 35
   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType) in GraphTypesLookup.cs: line 48
   at GraphQL.Types.Schema.CreateTypesLookup() in Schema.cs: line 171
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at GraphQL.Types.Schema.FindType(String name) in Schema.cs: line 128
   at GraphQL.Types.Schema.Initialize() in Schema.cs: line 64
   at GraphQL.Utilities.SchemaPrinter.PrintFilteredSchema(Func`2 directiveFilter, Func`2 typeFilter) in SchemaPrinter.cs: line 55
   at GraphQL.Utilities.SchemaPrinter.Print() in SchemaPrinter.cs: line 43
   at DocumentApi.GraphQL.Tests.ValidationTest.Test(String propType) in ValidationTest.cs: line 77

**Comment by diaconesq** [comment]
BTW this is a regression - it works before support for runtime unions.

**Comment by joemcbride** [comment]
Thanks for the report!  I'll take a look.

**Comment by joemcbride** [comment]
Published 0.14.3 with this fix.  https://www.nuget.org/packages/GraphQL/0.14.3.646

**Comment by joemcbride** [comment]
Btw, the need to register every type with the schema up front should also be fixed.

**Comment by diaconesq** [comment]
Wow, that was fast!
I confirm it's working - thanks a lot!
