### ISSUE TITLE
System.NullReferenceException on ResolveFieldContextAdapter after migration to 4.6.0

### ISSUE THREAD

**Issue by munterbusch-ms** [graphql-dotnet/graphql-dotnet#2650]
Hey everyone. 
Migrating to Graphql-dotnet 4.6.0 coming from 2.4.0 (...little late I guess), there is one particular issue that I am wondering about though there is a pretty easy workaround.
In the old version following code worked fine
```C#
Field<ListGraphType<MyListItemsGraphType>>()
    .Name("names")
    .Argument<ListGraphType<SomeFilterEnumGraphType>>("filterList", "Array of relevant filters.")
    .Resolve(context => context.Source.Names
                        .Where(los => context.GetArgument<Enums.SomeFilter[]>("filterList")?
                                      .Contains(los.filter) ?? false
    ));
```
but after the upgrade it results in following error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at GraphQL.ResolveFieldContextAdapter`1.get_ParentType() in /_/src/GraphQL/ResolveFieldContext/ResolveFieldContextAdapter.cs:line 62
   at GraphQL.ResolveFieldContextExtensions.TryGetArgument(IResolveFieldContext context, Type argumentType, String name, Object& result) in /_/src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs:line 37
   at GraphQL.ResolveFieldContextExtensions.GetArgument[TType](IResolveFieldContext context, String name, TType defaultValue) in /_/src/GraphQL/ResolveFieldContext/ResolveFieldContextExtensions.cs:line 20
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at GraphQL.Execution.ExecutionStrategy.SetArrayItemNodes(ExecutionContext context, ArrayExecutionNode parent) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 359
   at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 489
```

Saving the list of arguments in an additional var or copying the context and giving the copy into the linq-statement is working fine, so this is a workaround. For example:
```C#
Field<ListGraphType<MyListItemsGraphType>>()
    .Name("names")
    .Argument<ListGraphType<SomeFilterEnumGraphType>>("filterList", "Array of relevant filters.")
    .Resolve(context => 
    {
         var filterList=  context.GetArgument<Enums.SomeFilter[]>("filterList")?

         return context.Source.Names
                 .Where(los => filterList?.Contains(los.filter) ?? false);
    });
```

Did I miss something in the breaking changes that results in this behaviour? 
Would be great if you guys have an idea. 

Thanks in advance.

**Comment by Shane32** [comment]
The context may be re-used after the resolver executes, prior to enumeration of the list.  Since you are using `context` within the LINQ `Where` method, the `context` reference within the `Where` method is invalid at the time when then list is enumerated.  You have correctly identified a proper workaround, which is also faster since it will not need to parse the argument within every iteration.  Adding `.ToHashSet()` to your filter list may be even faster yet.

Other solutions are preserving/copying the context (prior to the `Where` statement) via `.Copy()`, or serializing the list with `.ToList()`.

See: https://graphql-dotnet.github.io/docs/migrations/migration4#code-classlanguage-textiresolvefieldcontextcode-re-use

**Comment by munterbusch-ms** [comment]
Now that was a really fast answer. 
I already assumed that the re-usage was the part resulting in the problem but wasn't sure. That is where I got the copy-idea from. 

Thanks a lot for clarifying.
