### ISSUE TITLE
Passing datetime as argument  - Antlr fails - Help

### ISSUE THREAD

**Issue by TLogik** [graphql-dotnet/graphql-dotnet#28]
Hi.
I am trying to pass a number of arguments to a Field.
Example below:
```
public ArticleSearchQuery()
        {
            Name = "Query";

            Field<ListGraphType<ArticleType>>("articles",
                arguments: new QueryArguments(
                    new[]
                    {
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "iql",
                            Description = "The Iql Query",
                            DefaultValue = string.Empty
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "startIndex",
                            Description = "The Index to start paging from",
                            DefaultValue = 0
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "pageSize",
                            Description = "The size of the page you want to received",
                            DefaultValue = "10"
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "searchFrom",
                            Description = "The datetime to search from. Format",
                            DefaultValue = DateTime.Now.ToString(CultureInfo.InvariantCulture)
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "searchTo",
                            Description = "The Index to start paging from",
                            DefaultValue = DateTime.Now.ToString(CultureInfo.InvariantCulture)
                        }
                    }),
                resolve:
                    context =>
                        Search((string) context.Arguments["iql"], int.Parse((string) context.Arguments["startIndex"]),
                            int.Parse((string) context.Arguments["pageSize"]),
                            (string) context.Arguments["searchFrom"],
                            (string) context.Arguments["searchTo"]));
```

Since i have mixed types i have chosen to use the `StringGraphType` and then manually convert the arguments when received.

I do however have a multitude of issues getting datetimes to be passed as a string argument.

I have tried variations:

Request via fiddler
```
{
  "Query": "{articles(iql:hund, startIndex:0, pageSize:12, searchFrom:2013-04-05T23, searchTo:2013-04-05T23){name}}"
}
```
Here Antlr fails with a *Reference not set to an object*
I have tried wrapping in quotes but then the queryobject is null.

I have tried:
```
{
  "Query": "{articles(iql:hund, startIndex:0, pageSize:12, searchFrom:2013-04-05T23:52:05.568Z, searchTo:2014-04-05T23:52:05.568Z){name}}"
}
```

And yet again Antrl fails.

Bottomline.
*How can i pass a string representing a DateTime that will allow Antlr to parse it correct?*

Exception StackTrace for brevity
```
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitArgument(ArgumentContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 215
   at GraphQL.Parsing.GraphQLParser.ArgumentContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 777
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitArguments(ArgumentsContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 205
   at GraphQL.Parsing.GraphQLParser.ArgumentsContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 716
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitField(FieldContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 326
   at GraphQL.Parsing.GraphQLParser.FieldContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 537
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitSelection(SelectionContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 361
   at GraphQL.Parsing.GraphQLParser.SelectionContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 464
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitSelectionSet(SelectionSetContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 348
   at GraphQL.Parsing.GraphQLParser.SelectionSetContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 349
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.VisitOperationDefinition(OperationDefinitionContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 385
   at GraphQL.Parsing.GraphQLParser.OperationDefinitionContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 268
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.VisitChildren(IRuleNode node)
   at GraphQL.Parsing.GraphQLBaseVisitor`1.VisitDefinition(DefinitionContext context) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLBaseVisitor.cs:line 55
   at GraphQL.Parsing.GraphQLParser.DefinitionContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 198
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Language.GraphQLVisitor.<>c__DisplayClass24_0.<VisitDocument>b__0(DefinitionContext childContext) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 411
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\EnumerableExtensions.cs:line 19
   at GraphQL.Language.GraphQLVisitor.VisitDocument(DocumentContext context) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Language\GraphQLVisitor.cs:line 409
   at GraphQL.Parsing.GraphQLParser.DocumentContext.Accept[TResult](IParseTreeVisitor`1 visitor) in E:\tbl\Programming\GitHub\graphql-dotnet\src\GraphQL\obj\Debug\GraphQLParser.cs:line 137
   at Antlr4.Runtime.Tree.AbstractParseTreeVisitor`1.Visit(IParseTree tree)
   at GraphQL.Execution.AntlrDocumentBuilder.Build(String data) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Execution\AntlrDocumentBuilder.cs:line 21
   at GraphQL.DocumentExecuter.Execute(Schema schema, Object root, String query, String operationName, Inputs inputs) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\GraphQL\Execution\DocumentExecuter.cs:line 38
   at Infomedia.PublishingServices.MediaResearch.Api.Controllers.GraphQl.ArticleSearchGraphQlController.Execute(Schema schema, Object rootObject, String query, String operationName, Inputs inputs) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\PS.MediaResearch.Api\Controllers\GraphQl\ArticleSearchGraphQlController.cs:line 38
   at Infomedia.PublishingServices.MediaResearch.Api.Controllers.GraphQl.ArticleSearchGraphQlController.Post(GraphQLQuery query) in E:\tbl\gitlab\infomedia-publishingservices-mediaresearch\PS.MediaResearch.Api\Controllers\GraphQl\ArticleSearchGraphQlController.cs:line 27
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Owin.PassiveAuthenticationMessageHandler.<SendAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.HttpServer.<SendAsync>d__0.MoveNext()
```

**Comment by joemcbride** [comment]
I haven't tried DateTime object yet so that could certainly be an issue.  As for strings, it doesn't look like those values are getting passed as string values to the API.

`searchFrom` and `searchTo` values should be wrapped in quotes to be considered valid strings.

```
{
  "Query": "{articles(iql:hund, startIndex:0, pageSize:12, searchFrom:'2013-04-05T23', searchTo:'2013-04-05T23'){name}}"
}
```

**Comment by joemcbride** [comment]
Was considering this and what I thought I remembered - the core GraphQL spec does not specify a `Date` object.  You can however define your own custom scalar ([as is shown in this example JavaScript implemenation](https://www.npmjs.com/package/graphql-custom-datetype)).  Can do the same in this project, something like:

```
public class DateGraphType : ScalarGraphType
{
    public DateGraphType()
    {
        Name = "Date";
    }

    public override object Coerce(object value)
    {
        DateTime result;
        if (DateTime.TryParse(value.ToString(), out result))
        {
            return result;
        }
        return null;
    }
}
```

**Comment by TLogik** [comment]
So there definitely is an issue here,
I am pretty sure that ANTLR has a issue parsing strings containing a datetime.

Below is the flow

*The query setup*
``` 
 public ArticleSearchQuery()
        {
            Name = "Query";

            Field<ListGraphType<ArticleType>>("articles",
                arguments: new QueryArguments(
                    new[]
                    {
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "iql",
                            Description = "The Iql Query",
                            DefaultValue = string.Empty
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "startIndex",
                            Description = "The Index to start paging from",
                            DefaultValue = 0
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "pageSize",
                            Description = "The size of the page you want to received",
                            DefaultValue = "10"
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "searchFrom",
                            Description = "The datetime to search from. Format",
                            DefaultValue = "searchFrom_FOO"//DateTime.Now.AddDays(-14).ToString(CultureInfo.InvariantCulture)
                        },
                        new QueryArgument<NonNullGraphType<StringGraphType>>
                        {
                            Name = "searchTo",
                            Description = "The Index to start paging from",
                            DefaultValue = "searchTo_BAR"//DateTime.Now.ToString(CultureInfo.InvariantCulture)
                        }
                    }),
                resolve:
                    context =>
                        Search((string) context.Arguments["iql"], int.Parse((string) context.Arguments["startIndex"]),
                            int.Parse((string) context.Arguments["pageSize"]),
                            (string) context.Arguments["searchFrom"],
                            (string) context.Arguments["searchTo"], context));
        }
````
Mark the rather NOT datetime defaults on the *searchFrom* and *searchTo*. Those are there to easily see that the default value is emitted rather than the passed argument.

*The rest request from fiddler/swagger*
```
{
  "Query": "{articles(iql:hund, startIndex:0, pageSize:12, searchFrom:'2015-04-05T23:52:05.568Z', searchTo:'2015-05-05T23:52:05.568Z'{
source
heading
subHeading
paragraph
captions
wordCount
}}"
}
```

*Here is what is recieved for processing in the code*

```
{articles(iql:hund, startIndex:0, pageSize:12, searchFrom:'2015-04-05T23:52:05.568Z', searchTo:'2015-05-05T23:52:05.568Z'{
source
heading
subHeading
paragraph
captions
wordCount
}}
```

The request sent and what is received match up perfectly. Especially the datetime entries are unprocessed and handed as simple strings.

*Here is what is emitted by the *context.Arguments* for the datetime fields after GraphQL processing/Parsing*

```
{[searchFrom, 2015]}
{[searchTo, searchTo_BAR]}
```

so it seems that the parser strips everything from the first *- dash* in *searchFrom* so that i only get *2015* and then *searchTo* will emit its default value.

From my days in ANTLR this seems to be a tokenizer issue. Could relate to the DSL definition not taking into account that an input could contain ´- dash´ and possible later on also `:`

I guess crreating a custom datetime scalar will not change this parser issue.

I hope my documentation is satisfactory.

I have not tried to modify the DSL. Mostly because i have not read the GraphQL fully so me editing the DSL will most definitely not be prudent at this time :-)

**Comment by joemcbride** [comment]
I'm not sure if it is an issue with your application or something else, though the examples you gave are not valid requests.  The `hund` value for `iql` needs to be surrounded with quotes.  You are also missing an ending `)` in the argument list.

It looks like the ANTLR grammar does have an issue with `2015-04-05T23:52:05.568Z` when using single-tic quotes.  If you change the `'` to `"` it will work.  [This branch/commit shows it working.](https://github.com/graphql-dotnet/graphql-dotnet/commit/9e1f5e211f04aaf916d2d523c82cb99edc36b48c)  The [official GraphQL spec](http://facebook.github.io/graphql/#sec-String-Value) calls for double-tic quotes so that was me miss-leading you there.  Sorry about that!

**Comment by TLogik** [comment]
> I'm not sure if it is an issue with your application or something else, though the examples you gave are not valid requests. The hund value for iql needs to be surrounded with quotes. You are also missing an ending ) in the argument list.

Correct. There was a missing `)`, but that was part of a copy past issue. Sorry about that. The actual query sent had the paranthesis.

The code is a basic ripoff of you starwars example, yet much simpler. And the request is handled just fine, except when an argument contains a `- dash`

If you look at the ex below:
```
{
  "Query": "{articles(iql:hund, startIndex:0, pageSize:5, searchFrom:2015-10-22){
heading
}"
}
```
you can see that the full value of Query is embedded in `" "` thus represents a full string.
All the parameters are parsed correct except when there is a `- dash` in the input argument.

Just to show that there is an issue with the dash i have done this:
```
{
  "Query": "{articles(iql:hu-nd, startIndex:0, pageSize:5{
heading
}"
}
```

and then the argument for `iql` after parsing is `hu`
So the parser is stripping the value after the `-`

I am running the version of tag 0.3.0.0 representing the latest deployed nugetpackage.

**Comment by joemcbride** [comment]
> you can see that the full value of Query is embedded in `" "` thus represents a full string

Yes, that `Query` property is a string, though I am speaking of GraphQL syntax, which is the string of data inside the `Query` property.

```
{
  "Query": "{articles(iql:hu-nd, startIndex:0, pageSize:5{
heading
}"
}
```

That query is not valid GraphQL syntax and will *not* work.  Besides the missing `)` again, there is also a miss-match of brackets.  The main issue:  `hu-nd` needs to be surrounded in quotes to represent a string in GraphQL syntax.

Here is your GraphQL query which is invalid:

```
{
  articles(iql:hu-nd, startIndex:0, pageSize:5 {
    heading
  }
```

This would be your query as valid GraphQL:

```
{
  articles(iql:"hu-nd", startIndex:0, pageSize:5) {
    heading
  }
}
```

Here is the JSON representation of the query which is expected in the sample project:
```
{
  "Query": "{articles(iql:\"hu-nd\", startIndex:0, pageSize:5) {heading}}"
}
```

**Comment by joemcbride** [comment]
I should also mention that your argument setup is also has some issues.

```
new QueryArgument<NonNullGraphType<StringGraphType>>
{
  Name = "startIndex",
  Description = "The Index to start paging from",
  DefaultValue = 0
},
```

Since you are setting the `startIndex` as a `StringGraphType` the `DefaultValue` should also be a `string` value.  You have given it a `DefaultValue` of `0` which is an integer.

With your setup this is still technically invalid:

```
{
  articles(iql:"hu-nd", startIndex:0, pageSize:5) {
    heading
  }
}
```

And should be changed to:
```
{
  articles(iql:"hu-nd", startIndex:\"0\", pageSize:\"5\") {
    heading
  }
}
```

If you want to use integers for `startIndex` and `pageSize` you can update the arguments to this:

```
public ArticleSearchQuery()
{
    Name = "Query";

    Field<ListGraphType<ArticleType>>("articles",
        arguments: new QueryArguments(
            new QueryArgument[]
            {
                new QueryArgument<NonNullGraphType<StringGraphType>>
                {
                    Name = "iql",
                    Description = "The Iql Query",
                    DefaultValue = string.Empty
                },
                new QueryArgument<NonNullGraphType<IntGraphType>>
                {
                    Name = "startIndex",
                    Description = "The Index to start paging from",
                    DefaultValue = 0
                },
                new QueryArgument<NonNullGraphType<IntGraphType>>
                {
                    Name = "pageSize",
                    Description = "The size of the page you want to received",
                    DefaultValue = 10
                },
                new QueryArgument<NonNullGraphType<StringGraphType>>
                {
                    Name = "searchFrom",
                    Description = "The datetime to search from. Format",
                    DefaultValue = "searchFrom_FOO"//DateTime.Now.AddDays(-14).ToString(CultureInfo.InvariantCulture)
                },
                new QueryArgument<NonNullGraphType<StringGraphType>>
                {
                    Name = "searchTo",
                    Description = "The Index to start paging from",
                    DefaultValue = "searchTo_BAR"//DateTime.Now.ToString(CultureInfo.InvariantCulture)
                }
            }),
        resolve:
            context =>
                Search((string) context.Arguments["iql"], int.Parse((string) context.Arguments["startIndex"]),
                    int.Parse((string) context.Arguments["pageSize"]),
                    (string) context.Arguments["searchFrom"],
                        (string) context.Arguments["searchTo"], context));
    }
}
```

I think the design of the code for these things can and should be improved so that you get compile-time errors when you miss-match types.  Query validation should also help when that is worked on.  As this project is pretty new (and mostly a one-man-show) there are issues like this.

**Comment by TLogik** [comment]
> Since you are setting the startIndex as a StringGraphType the DefaultValue should also be a string value. You have given it a DefaultValue of 0 which is an integer.

Thakns. I had already fixed that :-)

>Here is the JSON representation of the query which is expected in the sample project:

That indeed fixed it. It assumed that wrapping everything as a string was valid. It will actually parse it correctly (when no `-` is present).

Thanks for your support.
Ill give the DateTime scalar type a try later on.
