### ISSUE TITLE
Interfaces failed on sub types fields

### ISSUE THREAD

**Issue by mJustGER** [graphql-dotnet/graphql-dotnet#3023]
Hi,

my graphql works very well and offers several querys and mutations.
Now i need to offer a sub field as list of images videos and so on.
These types have the same base type.

But since i integrate interfaces and also unions i run into errors.
The enviroment is .net 6, asp core, c#, graphql 4.7

**some docu links:**
- [notes about graphql interfaces](https://graphql-dotnet.github.io/docs/getting-started/interfaces)
- [grphql example about interfaces](https://github.com/graphql-dotnet/graphql-dotnet/tree/master/src/GraphQL.StarWars)

## The models are like this
```
public class Point 
{
        public string Title { get; set; }
        public List<IMedia> Media { get; set; }
}

public abstract class IMedia
{
        public Uri Uri { get; set; }
        public string MimeType { get; set; }
}

public class Image : IMedia
{
     public string Resolution { get; set; }
     public string Color { get; set; }
}
```

## The graph types are like this
```
public class PointType :  ObjectGraphType<Point>
{
        public PointType()
        {
            Name = "PointType";
            Field(x => x.Title, nullable: true, typeof(TitleType)).Description("title filed");
            Field(x => x.Media, nullable: true, type: typeof(ListGraphType<MediaInterface>)).Description("media filed");
        }
}

public class MediaInterface : InterfaceGraphType<IMedia>
{
 
        public MediaInterface()
        {
            Name = "MediaInterface";
            Field(x => x.MimeType, nullable: true).Description("MimeType filed");
            Field(x => x.Uri, nullable: true).Description("Uri filed");
        }
}

public class ImageType : ObjectGraphType<Image>
{
        public ImageType()
        {
            Name = "ImageType";
            Field(x => x.Resolution , nullable: true);
            Field(x => x.Color , nullable: true);
        }
}
```

## Graphql query type
```
 Field<PointType>("createPoint",  arguments: new QueryArguments(
              new QueryArgument<PointInputType>() { Name = "data", Description = "add Point data" }),
              resolve : context =>
                {
                    var item = context.GetArgument<Point>("data");
                    var loader = _accessor.Context.GetOrAddLoader("CreateLocationItem", () => _locationStore.CreatePointAsync(item));
                    return loader.LoadAsync();
                });
```

## The Execution problem
When execution the graphql query everything ends in this exception.
Before we added interfactes erverything works well.

```
fail: GC.API.GraphQL.Queries.Startup[0]
      Abstract type MediaInterface must resolve to an Object type at runtime for field .media with value 'GC.API.GraphQL.Models.Location.Object.Media.Image', received 'null'. occurred


fail: GC.API.GraphQL.Queries.Startup[0]
      Abstract type MediaInterface must resolve to an Object type at runtime for field .media with value 'GC.API.GraphQL.Models.Location.Object.Media.Video', received 'null'. occurred
fail: GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware[0]
      GraphQL execution completed in 00:00:02.3170860 with error(s): GraphQL.Execution.UnhandledError: Error trying to resolve field 'media'.
       ---> System.InvalidOperationException: Abstract type MediaInterface must resolve to an Object type at runtime for field .media with value 'GC.API.GraphQL.Models.Location.Object.Media.Image', received 'null'.
         at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 580
         at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 505
         --- End of inner exception stack trace ---, GraphQL.Execution.UnhandledError: Error trying to resolve field 'media'.
       ---> System.InvalidOperationException: Abstract type MediaInterface must resolve to an Object type at runtime for field .media with value 'GC.API.GraphQL.Models.Location.Object.Media.Video', received 'null'.
         at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 580
         at GraphQL.Execution.ExecutionStrategy.CompleteNode(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 505
         --- End of inner exception stack trace ---
```

## My Question
I didn´t found any docu about unions or interfaces in sub fields - is this even possible?
And why the interface dont find any data? the model contains a list of media objects?

Does anyone know why it doesn´t work?

**Comment by Benkhouds** [comment]
I had the same issue, can someone help here please :(

**Comment by Shane32** [comment]
@Benkhouds can you provide samples of your code and the error message you are receiving, along with a list of the GraphQL nuget packages you have installed and what versions they are

**Comment by sungam3r** [comment]
I suggest to upgrade to the letestavailable version - 7.3.1 for the time of writing. I think this is one of bugs during schema initialization. Error message you provide contains empty type name - see `.media`. There should be type name before dot.

**Comment by Shane32** [comment]
Please ask if there are further questions on this topic
