### ISSUE TITLE
Upgrade to v5 of graphql-dotnet not working

### ISSUE THREAD

**Issue by StefanGies99** [graphql-dotnet/graphql-dotnet#3085]
## Summary

Hello all,

Currently I'm trying to upgrade towards the latest version of graphql-dotnet because I'm facing some issues listed in #3002. I was trying to accomplish this by upgrading the following packages to it's latest versions: 

```
<PackageReference Include="GraphQL" Version="5.1.1" />
<PackageReference Include="GraphQL.MicrosoftDI" Version="5.1.1" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="5.2.1" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.2.1" />
<PackageReference Include="GraphQL.Server.Transports.Subscriptions.WebSockets" Version="5.2.1" />    
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.2.1" />
<PackageReference Include="GraphQL.SystemTextJson" Version="5.1.1" />
```

## Relevant information

I followed the steps mentioned in the migration page of the [docs](https://graphql-dotnet.github.io/docs/migrations/migration5/) but I'm facing the following error where I have no clue what I need to do: 

```
Unhandled exception. System.MissingMethodException: Method not found: 'GraphQL.DI.IGraphQLBuilder GraphQL.DI.IGraphQLBuilder.TryRegister(System.Type, System.Type, GraphQL.DI.ServiceLifetime)'.
   at GraphQL.Server.GraphQLBuilderCoreExtensions.AddServer(IGraphQLBuilder builder, Boolean installMetricsMiddleware, Action`1 configureOptions)
   at MobileApi.Api.Startup.<>c.<AddGraphQL>b__9_2(IGraphQLBuilder configure) in /Users/user1/src/Api/Startup.cs:line 203
   at GraphQL.MicrosoftDI.GraphQLBuilder..ctor(IServiceCollection services, Action`1 configure) in /_/src/GraphQL.MicrosoftDI/GraphQLBuilder.cs:line 36
   at GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(IServiceCollection services, Action`1 configure) in /_/src/GraphQL.MicrosoftDI/GraphQLBuilderExtensions.cs:line 23
   at MobileApi.Api.Startup.AddGraphQL(IServiceCollection services, IHostEnvironment environment, Boolean enableListener) in /Users/user1/src/Api/Startup.cs:line 203
   at MobileApi.Api.Startup.ConfigureServices(IServiceCollection services) in /Users/user1/src/Api/Startup.cs:line 143
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MobileApi.Api.Program.Main(String[] args) in /Users/user1/src/Api/Program.cs:line 9
```

Could someone give me a hand resolving this issue I'm currently facing? 

### Environment (if relevant)

I don't think it's relevant but I'm using dotnet core 3.1 at the moment and will move towards net6 soon.

**Comment by sungam3r** [comment]
@Shane32 What about https://github.com/graphql-dotnet/server/pull/761 and especially https://github.com/graphql-dotnet/server/pull/762 ? Let's finish, merge and publish Server v6.

**Comment by Shane32** [comment]
> 

I'm sorry I didn't see that you had reviewed those PRs.  I will work on them today.
