### ISSUE TITLE
Issues upgrading to GQL v 5.1.1 (IDocumentWriter error)

### ISSUE THREAD

**Issue by giy** [graphql-dotnet/graphql-dotnet#3090]
## Summary
Hello, I am trying to upgrade to GQL v 5.1.1 and getting the following error,
```
System.TypeLoadException: Could not load type 'GraphQL.IDocumentWriter' from assembly 'GraphQL, Version=5.1.1.0, Culture=neutral, PublicKeyToken=null'.
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddGraphQL(IServiceCollection services, Action`2 configureOptions)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddGraphQL(IServiceCollection services, Action`1 configureOptions) in /_/src/Core/Extensions/ServiceCollectionExtensions.cs:line 35
```

## Relevant information

Based on the docs, https://graphql-dotnet.github.io/docs/migrations/migration5 No.17 I've already made this change,
```
services.AddSingleton<IGraphQLSerializer, GraphQLSerializer>();
```
replacing,
```
services.AddSingleton<IDocumentWriter, GraphQL.SystemTextJson.DocumentWriter>();
```

and hooking,
```
services.AddGraphQL((options) =>
            {
                options.EnableMetrics = false;
            })
            .AddErrorInfoProvider(opt => opt.ExposeExceptionStackTrace = true)
            .AddSystemTextJson()
            .AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User });
        }
```

### Environment (if relevant)
Dependencies,
```
    <PackageReference Include="GraphQL.DataLoader" Version="5.1.1" />
    <PackageReference Include="GraphQL.MicrosoftDI" Version="5.1.1" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore.SystemTextJson" Version="5.2.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="5.1.1" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="5.2.1" />
    <PackageReference Include="GraphQL" Version="5.1.1" />
```

I am not sure as to why I am still getting the IDocumentWriter error and would appreciate any assistance. Thank you!

**Comment by Shane32** [comment]
GraphQL Server v5 is compatible with GraphQL v4.  GraphQL Server v6 is compatible with GraphQL v5.

**Comment by giy** [comment]
Oh, I see. That resolved it. Thank you.
