### ISSUE TITLE
Issue with EnumerationGraphType in mutations (v5)

### ISSUE THREAD

**Issue by kamnyborg** [graphql-dotnet/graphql-dotnet#3139]
## Summary
Hi, I'm having an issue with the upgrade of GraphQL.NET from v3 -> v5. I have a mutation that passes in a string value that should be interpreted as an EnumerationGraphType, but I get the error message "Variable '$field' is invalid. Unable to convert 'Title' to 'StringField'". 

## Relevant information
The mutation looks like this:
```
 mutation ($field: StringField!, $command: ChangeActionStringCommandInput!){
                response: changeActionStringField(field: $field, command: $command){
                    modifiedDate
                }
            }
```
With variables:
```
{{
  "field": "Title",
  "command": {
    "actionId": 1,
    "prevValue": "",
    "newValue": "Test Title"
  }
}}
```

On the server side, the mutation is configured like this:
```
 Field<NonNullGraphType<ChangeActionResultType>>()
                .Name("changeActionStringField")
                .Argument<NonNullGraphType<ActionStringFieldEnumType>>("field", "The action field to mutate")
                .Argument<NonNullGraphType<ChangeActionStringCommandInputType>>("command", "")
                .ResolveAsync(async context =>
                { (..)
```
```
 public class ActionStringFieldEnumType : EnumerationGraphType<StringField>
    {}
```
```
 public enum StringField
    {
        Title,
        Description,
        SapNotificationReference,
        SapWorkOrderReference,
        ServiceNowReference,
        Risk,
    }
```
I have updated the controller according to migrations docs like this:
```
public async Task Post([FromBody] GraphQlQuery query, [Microsoft.AspNetCore.Mvc.FromServices] EntityContext dbContext)
        {
            if (query == null) { throw new ArgumentNullException(nameof(query)); }

            var graphQlContext = new GraphQlContext { DbContext = dbContext, CorrelationId = HttpContext.GetCorrelationId(), User = User };
            var variables = query.Variables == null ? null : _serializer.ReadNode<Inputs>(query.Variables);

            var executionOptions = new ExecutionOptions
            {
                Schema = _schema,
                Query = query.Query,
                Variables = variables,
                UserContext = graphQlContext,
                EnableMetrics = !IsProduction,
                Listeners = { _dataLoaderDocumentListener },
                ValidationRules = DocumentValidator.CoreRules.Concat(_validationRules)
            };

            var result = await _documentExecuter.ExecuteAsync(executionOptions);
            await _writer.WriteAsync(Response.Body, result, CancellationToken.None);
        }
```

What happens when I post the mutation is that I get the error message:
"Variable '$field' is invalid. Unable to convert 'Title' to 'StringField'"

Part of stack:
```
 at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValueScalar|49_1(ScalarGraphType scalarGraphType, GraphQLVariableDefinition variableDef, VariableName variableName, Object value) in /_/src/GraphQL/Validation/ValidationContext.cs:line 253
   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValue|49_0(IGraphType type, GraphQLVariableDefinition variableDef, VariableName variableName, Object value, IVariableVisitor visitor) in /_/src/GraphQL/Validation/ValidationContext.cs:line 234
   at GraphQL.Validation.ValidationContext.<GetVariableValue>g__ParseValue|49_0(IGraphType type, GraphQLVariableDefinition variableDef, VariableName variableName, Object value, IVariableVisitor visitor) in /_/src/GraphQL/Validation/ValidationContext.cs:line 240
   at GraphQL.Validation.ValidationContext.GetVariableValues(IVariableVisitor visitor) in /_/src/GraphQL/Validation/ValidationContext.cs:line 156
```

I created an override in the ActionStringFieldEnumType like this, which made it work:
```
 public override object ParseValue(object value)
        {
            Enum.TryParse((string)value, out StringField stringField);
            return stringField;
        }
```
However, this seems to be a workaround, do you have a proposal?

I have read the migration guides (v3->v4 and v4->v5), but there doesn't seem like anything is changed except the parsing of exact names, which should not be a problem in this case.

### Environment (if relevant)
```
 <PackageReference Include="GraphQL" Version="5.2.0" />
    <PackageReference Include="GraphQL.DataLoader" Version="5.2.0" />
    <PackageReference Include="GraphQL.EntityFramework" Version="17.1.0" />
    <PackageReference Include="GraphQL.MicrosoftDI" Version="5.2.0" />
    <PackageReference Include="GraphQL.NewtonsoftJson" Version="5.2.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="6.0.0" />
    <PackageReference Include="GraphQL.Server.Transports.Subscriptions.WebSockets" Version="6.0.0" />
```

**Comment by Shane32** [comment]
Typically enum names are converted to constant case, which would be “TITLE” rather than “Title”. Did you check if this is the issue?

**Comment by kamnyborg** [comment]
You are right, that is actually the issue! Considering the client already has configured the values for the enums in pascal case, it is not clear to me from the docs how to keep the "old" functionality (https://graphql-dotnet.github.io/docs/migrations/migration5/#26-code-classlanguage-textenumerationgraphtypecode-parses-exact-names). But I found you answer on another question with the CaseInsensitiveEnumerationGraphType: https://github.com/graphql-dotnet/graphql-dotnet/issues/3105#issuecomment-1109991628. Thanks!
