### ISSUE TITLE
GraphQL Serialization ObjectConverter NotSupportedException only online

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/graphql-dotnet#3233]
## Description

I added an unhandledExceptionDelegate in my GraphQLMiddleware.  In this middleware I have logic that adds info to the logged error. This enriches the data we see in Azure App Insights. When I trigger errors locally everything works well: I get the error in Azure with all the extra info, and I get a clean graphQL error as response. But when I do the same thing online it doesn't work and returns a NotSupportedException from System.Text.Json.Serialization.Converters.ObjectConverter.

### Steps to reproduce

**GraphQLMiddleware.cs**
```
private async Task ExecuteAsync(HttpContext context, ISchema schema, IEnvHelper envHelper,
    DataLoaderDocumentListener dataLoaderDocumentListener, IRequestContext requestContext,
    ILogger<GraphQLMiddleware> logger)
{
    var start = DateTime.UtcNow;

    GraphQLRequest graphQLRequest = await _graphQLSerializer.ReadAsync<GraphQLRequest>(context.Request.Body, context.RequestAborted);
    var enableMetrics = envHelper.CurrentEnvironment() switch
    {
        EnvironmentEnum.Local or EnvironmentEnum.Dev or EnvironmentEnum.Staging => true,
        EnvironmentEnum.Production => false,
        _ => throw new NotImplementedException(),
    };
    var result = await _executer.ExecuteAsync(options =>
    {
        options.Schema = schema;
        options.Query = graphQLRequest.Query;
        options.OperationName = graphQLRequest.OperationName;
        options.Variables = graphQLRequest.Variables;
        options.UserContext = GenerateGraphQLUserContext(context);
        options.EnableMetrics = enableMetrics;
        options.RequestServices = context.RequestServices;
        options.CancellationToken = context.RequestAborted;
        options.Listeners.Add(dataLoaderDocumentListener);
        options.ThrowOnUnhandledException = false;
        options.ValidationRules = context.RequestServices.GetServices<IValidationRule>().Concat(DocumentValidator.CoreRules);
        options.UnhandledExceptionDelegate = ctx =>
        {
            return HandleErrors(context, ctx, graphQLRequest, requestContext, logger);
        };
    });

    if (enableMetrics)
    {
        result.EnrichWithApolloTracing(start);
    }

    await WriteResponseAsync(context, result, context.RequestAborted);
}

private async Task WriteResponseAsync(HttpContext context, ExecutionResult result,
    CancellationToken cancellationToken)
{
    context.Response.ContentType = "application/json";

    await _graphQLSerializer.WriteAsync(context.Response.Body, result, cancellationToken);
}
private Task HandleErrors(HttpContext context, UnhandledExceptionContext exceptionCtx, GraphQLRequest graphQLRequest,
    IRequestContext requestContext, ILogger<GraphQLMiddleware> logger)
{
    // Set HTTP Status Code
    int code = StatusCodes.Status500InternalServerError;

    if (exceptionCtx.Exception is AppUserException)
    {
        code = StatusCodes.Status400BadRequest;
        exceptionCtx.ErrorMessage = exceptionCtx.Exception.Message;
    }
    context.Response.StatusCode = code;

    // Additional Info
    // must be value type object
    Dictionary<string, object> customProperties = new();

    // Log Request
    string graphQLQuery = graphQLRequest.Query;
    customProperties.Add("GraphQL query", graphQLQuery);

    // Log Variables
    string graphQLVariables = JsonConvert.SerializeObject(graphQLRequest.Variables);
    customProperties.Add("GraphQL variables", graphQLVariables);

    using (logger.BeginScope(customProperties))
    {
        logger.LogError(exceptionCtx.Exception, exceptionCtx.Exception.Message, customProperties);
    }
    return Task.CompletedTask;
}
```

### Expected result

1. I should also get the error when I run the code locally. (same environment, even when running in release mode)
2. I should get the error thrown in the app, not this serialization exception.

### Actual result

Locally:
```
{
	"errors": [
		{
			"message": "MyError: UserException: Entries must have a linked project. The setting for this is turned on.",
			"locations": [
				{
					"line": 2,
					"column": 3
				}
			],
			"path": [
				"createEntry"
			],
			"extensions": {
				"code": "APP_USER",
				"codes": [
					"APP_USER"
				]
			}
		}
	],
	"data": {
		"createEntry": null
	},
	"extensions": {
		"tracing": {
			"version": 1,
			"startTime": "2022-07-18T12:36:59.9310053Z",
			"endTime": "2022-07-18T12:37:31.3260053Z",
			"duration": 31394966799,
			"parsing": {
				"startOffset": 1248314800,
				"duration": 46084499
			},
			"validation": {
				"startOffset": 1297129300,
				"duration": 11528643500
			},
			"execution": {
				"resolvers": []
			}
		}
	}
}
```

**Online:**
```
System.NotSupportedException: The type 'System.Object' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.ObjectConverter'. Path: $.
 ---> System.NotSupportedException: The type 'System.Object' is not a supported dictionary key using converter of type 'System.Text.Json.Serialization.Converters.ObjectConverter'.
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DictionaryKeyTypeNotSupported(Type keyType, JsonConverter converter)
   at System.Text.Json.Serialization.Converters.ObjectConverter.WriteAsPropertyNameCore(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, Boolean isWritingExtensionDataProperty)
   at System.Text.Json.Serialization.Converters.IDictionaryConverter`1.OnWriteResume(Utf8JsonWriter writer, TDictionary value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.DictionaryDefaultConverter`3.OnWriteResume(Utf8JsonWriter writer, TDictionary value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryWrite(Utf8JsonWriter writer, TDictionary dictionary, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at GraphQL.SystemTextJson.ExecutionErrorJsonConverter.Write(Utf8JsonWriter writer, ExecutionError error, JsonSerializerOptions options) in /_/src/GraphQL.SystemTextJson/ExecutionErrorJsonConverter.cs:line 58
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](Utf8JsonWriter writer, TValue value, JsonSerializerOptions options)
   at GraphQL.SystemTextJson.ExecutionResultJsonConverter.Write(Utf8JsonWriter writer, ExecutionResult value, JsonSerializerOptions options) in /_/src/GraphQL.SystemTextJson/ExecutionResultJsonConverter.cs:line 24
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at MyApp.Api.GraphQL.GraphQLMiddleware.WriteResponseAsync(HttpContext context, ExecutionResult result, CancellationToken cancellationToken) in D:\a\1\s\MyApp\MyApp.Api\GraphQL\GraphQLMiddleware.cs:line 116
   at MyApp.Api.GraphQL.GraphQLMiddleware.ExecuteAsync(HttpContext context, ISchema schema, IEnvHelper envHelper, DataLoaderDocumentListener dataLoaderDocumentListener, IRequestContext requestContext, ILogger`1 logger) in D:\a\1\s\MyApp\MyApp.Api\GraphQL\GraphQLMiddleware.cs:line 108
   at MyApp.Api.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, ISchema schema, IEnvHelper envHelper, DataLoaderDocumentListener dataLoaderDocumentListener, IRequestContext requestContext, ILogger`1 logger) in D:\a\1\s\MyApp\MyApp.Api\GraphQL\GraphQLMiddleware.cs:line 52
   at MyApp.Common.Middlewares.ApiMiddleware.InvokeAsync(HttpContext httpContext, IRequestContext requestContext, ITenantUserResource tenantUserResource, IEnvHelper env, ILoginManager loginManager, ITelemetryHelper telemetryHelper) in D:\a\1\s\MyApp\MyApp.Common\Middelwares\ApiMiddleware.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

The error references an object used as key, which I don't have. Even the extra logging uses a string as key. And even when I change it to value string I still get the error (and azure app insights requires the value to be an object.).

### Environment

Project: .NET 6.0
Packages:
```
    <PackageReference Include="GraphQL" Version="5.3.2" />
    <PackageReference Include="GraphQL.Authorization" Version="5.0.0" />
    <PackageReference Include="GraphQL.DataLoader" Version="5.3.2" />
    <PackageReference Include="GraphQL.MemoryCache" Version="5.3.2" />
    <PackageReference Include="GraphQL.MicrosoftDI" Version="5.3.2" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="6.1.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="6.1.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="5.3.2" />
```

**Comment by Shane32** [comment]
Everything looks fine.  It seems very unusual that a dictionary/object could be presented to the serialization engine as a property name.  And `customProperties` is stored anywhere in the response, that I can tell, so it should not matter how that is constructed.

I suggest two things:

1. Assert that `exceptionCtx.ErrorMessage = exceptionCtx.Exception.Message` does not set an empty string or null.

```cs
if (string.IsNullOrWhiteSpace(exceptionCtx.ErrorMessage))
    exceptionCtx.ErrorMessage = "Can't identify error";
```

2. Try registering an `ErrorInfoProvider` class (as `IErrorInfoProvider`) with `options.ExposeData = false`

```cs
services.AddSingleton<IErrorInfoProvider>(new ErrorInfoProvider(o => o.ExposeData = false));
```

Does the problem happen if you do not set `UnhandledExceptionDelegate`?  If not, I'd start by commenting out this code and see if the issue goes away (it shouldn't, because `customProperties` isn't stored in the response):

```cs

    // Additional Info
    // must be value type object
    Dictionary<string, object> customProperties = new();

    // Log Request
    string graphQLQuery = graphQLRequest.Query;
    customProperties.Add("GraphQL query", graphQLQuery);

    // Log Variables
    string graphQLVariables = JsonConvert.SerializeObject(graphQLRequest.Variables);
    customProperties.Add("GraphQL variables", graphQLVariables);

    using (logger.BeginScope(customProperties))
    {
        logger.LogError(exceptionCtx.Exception, exceptionCtx.Exception.Message, customProperties);
    }
```

If removing that code makes the problem disappear, you'll need to investigate how changing `customProperties` affects a seemingly-unrelated execution response.  And if not, then it would seem to have to do with setting the `ErrorMessage` property...

I did notice that you are using Newtonsoft.Json to serialize the request variables within `customProperties`.  But the problem isn't occuring within Newtonsoft, and it's just a string afterwards.  So that shouldn't matter.

**Comment by julienFlexsoft** [comment]
I commented this out:
```
using (logger.BeginScope(customProperties))
    {
        logger.LogError(exceptionCtx.Exception, exceptionCtx.Exception.Message, customProperties);
    }
```
And now it works. I'll keep investigating why but I'm running out of ideas. The two main question I seek to answer are:

1. What is the cause of the issue?
2. Why does it only happen online?

It only happens when it runs on our Azure App Service (and on multiple environments). When I run the code locally it works perfectly (Release and debug).

**Comment by Shane32** [comment]
Can you try adding an ErrorInfoProvider that set to not-include data?

```cs
.AddErrorInfoProvider(o => o.ExposeData = false)
```

**Comment by julienFlexsoft** [comment]
Adding this line has fixed the issue.
```
services.AddSingleton<IErrorInfoProvider>(new ErrorInfoProvider(o => o.ExposeData = false));
```

I'm still not really sure why, but everything works now.
Thank you for your help!

**Comment by Shane32** [comment]
No problem

**Comment by sungam3r** [comment]
> I'm still not really sure why, but everything works now.

Because one of exception in your response contains `object` as a key in `Exception.Data` property.
