### ISSUE TITLE
Space in ObjectGraphType Name property not handled

### ISSUE THREAD

**Issue by SpiraMira** [graphql-dotnet/graphql-dotnet#3343]
Adding a space in the Name field ("The Queries" versus "Queries") below generates the following DI related error in my PlayGround:

```
{
  "error": "JSON Parse error: Unexpected identifier \"Castle\""
}
```
Yes, "Castle" as in "Castle Windsor" Dependency Injection which my project uses...

- I'm not aware of any restrictions to the StringType of the Name property
- How can I add better Error Handling to get more details on this error (took a while to find this!)

```
    public class QueryObject : ObjectGraphType<object>, ITransientDependency
    {
        public Log Log { get; private set; }

        private readonly MovieRepository _movieRepository;

        public QueryObject(MovieRepository repository, Log log)
        {
            Name = "The Queries";
            Description = "The base query for all the entities in our object graph.";
            _movieRepository = repository; 
            Log = log;

            Field<MovieObject>("movie")
                .Argument<NonNullGraphType<IdGraphType>>("id", "id of the movie")
                // .ResolveAsync(async context => await _movieRepository.GetMovieByIdAsync(context.GetArgument("id", Guid.Empty)));
                .ResolveAsync(async context => {
                    var result = await _movieRepository.GetMovieByIdAsync(context.GetArgument("id", Guid.Empty));
                    if (result == null)
                        throw new ExecutionError("Invalid order id");
                        return result;
                });

        }
    }
```

Environment:
macOS
.net 6
latest GraphQL (7.1.1)
VSCode

**Comment by Shane32** [comment]
I suggest using the browser's developer mode to view the network traffic of the request and see what the exact text is that is being returned from the server.

**Comment by SpiraMira** [comment]
- Looks like it breaks in the in /_/src/GraphQL/Utilities/NameValidator.cs:line 50

A type name must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'The Queries' does not. (Parameter 'name')

- Something wrong(?) with the regex (?) OR As intended ...

Here's the output 

```
Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate aqua.Schemas.MainSchema
 ---> System.Exception: Could not instantiate aqua.Schemas.MainSchema.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate MovieReviews.GraphQL.QueryObject
 ---> System.ArgumentOutOfRangeException: A type name must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'The Queries' does not. (Parameter 'name')
   at GraphQL.Utilities.NameValidator.<ValidateDefault>g__ThrowMatchError|2_0(<>c__DisplayClass2_0& ) in /_/src/GraphQL/Utilities/NameValidator.cs:line 50
   at GraphQL.Utilities.NameValidator.ValidateDefault(String name, NamedElement type) in /_/src/GraphQL/Utilities/NameValidator.cs:line 45
   at GraphQL.Utilities.NameValidator.ValidateName(String name, NamedElement type) in /_/src/GraphQL/Utilities/NameValidator.cs:line 13
   at GraphQL.Types.GraphType.SetName(String name, Boolean validate) in /_/src/GraphQL/Types/GraphType.cs:line 67
   at GraphQL.Types.GraphType.set_Name(String value) in /_/src/GraphQL/Types/GraphType.cs:line 81
   at MovieReviews.GraphQL.QueryObject..ctor(MovieRepository repository, Log log) in /Users/pkouame/dev/aqua/KUVU/KUVU/src/aqua.GraphQL/Examples/Movie/GraphQL/QueryObject.cs:line 35
   at lambda_method2975(Closure , Object[] )
   at Castle.Core.Internal.ReflectionUtil.Instantiate[TBase](Type subtypeofTBase, Object[] ctorArgs)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstanceCore(ConstructorCandidate constructor, Object[] arguments, Type implType)
   --- End of inner exception stack trace ---
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstanceCore(ConstructorCandidate constructor, Object[] arguments, Type implType)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstance(CreationContext context, ConstructorCandidate constructor, Object[] arguments)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetServiceInternal(Type serviceType, Boolean isOptional)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at aqua.Schemas.MainSchema..ctor(IServiceProvider provider) in /Users/pkouame/dev/aqua/KUVU/KUVU/src/aqua.GraphQL/Schemas/MainSchema.cs:line 21
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at Castle.Core.Internal.ReflectionUtil.Instantiate[TBase](Type subtypeofTBase, Object[] ctorArgs)
   --- End of inner exception stack trace ---
   at Castle.Core.Internal.ReflectionUtil.Instantiate[TBase](Type subtypeofTBase, Object[] ctorArgs)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstanceCore(ConstructorCandidate constructor, Object[] arguments, Type implType)
   --- End of inner exception stack trace ---
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstanceCore(ConstructorCandidate constructor, Object[] arguments, Type implType)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateInstance(CreationContext context, ConstructorCandidate constructor, Object[] arguments)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.<>c__DisplayClass4_0.<Resolve>b__0(Action`1 afterCreated)
   at Castle.MicroKernel.Lifestyle.Scoped.DefaultLifetimeScope.GetCachedInstance(ComponentModel model, ScopedInstanceActivationCallback createInstance)
   at Castle.MicroKernel.Lifestyle.ScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.Windsor.MsDependencyInjection.MsScopedLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.Windsor.MsDependencyInjection.ScopedWindsorServiceProvider.GetServiceInternal(Type serviceType, Boolean isOptional)
   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 27
   at GraphQL.Utilities.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider) in /_/src/GraphQL/Utilities/ServiceProviderExtensions.cs:line 11
   at GraphQL.DocumentExecuter`1.ExecuteAsync(ExecutionOptions options) in /_/src/GraphQL/Execution/DocumentExecuter.cs:line 308
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware.ExecuteRequestAsync(HttpContext context, GraphQLRequest request, IServiceProvider serviceProvider, IDictionary`2 userContext) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 420
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware.HandleRequestAsync(HttpContext context, RequestDelegate next, GraphQLRequest gqlRequest) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 299
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware.InvokeAsync(HttpContext context) in /_/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs:line 177
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IBackChannelLogoutService backChannelLogoutService)
   at IdentityServer4.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.Ic8UST3TYlelsLKPpP4.MoveNext()
--- End of stack trace from previous location ---
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.Ic8UST3TYlelsLKPpP4.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: */*, application/json
Connection: keep-alive
Host: localhost:44301
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Content-Type: application/json
Cookie: .AspNetCore.Identity.Application=CfDJ8PL4AaNuMwVFiNQ23RL0Qz22m4kMsOHeqjHhBeQWbyObvSiQLOi52xqZnZJNlwuzkA6NOcCV9Vr7uEH38lCHxSvK8qp7g50lzHrtTvsHe-QzAROgqKjxfA3itl0qztB6tqTkLuxCmaoGoxqHRc04WT3GJcBck_FKGd-kalVNT_hJZl4AotzjISk9A7E3g1EHSwO_doxkbLwyH-5Zn9FihKuxGwZP2OQZyY00El_rJqXBGkkeh4_UhkVIqaf2umSkRDgqkJw_Xa1wdoZbxoMEEK2uaes5NSVT3e3bvd_RD7iSDiN0GKbWjgqi08OfNybe3qr46ciQZ6_7TUo5yq7R3kvdreSbpfYW8jEVrqhxQTNVWwWdscxIu1sYMDlmxT6TI8Nzpo5maUQdnnPfEMdAs0afhkJPQg4k8YW4j5HwBClz09wv4r3qrE_83imOZKz_uwl-fwk2xmZz3ArxfhG5LqCpyntFUMIWgP-WL34EPxDNOyRYTJvB3AF2hGG0XZ8jCgflavnpxkS70AbxTZnOUtFTXrP8T8ORb-ikZUhToE6ne3ZLebhx9WAsQGwg_wB70a4bEDSHcNQegwEusflmarPd_sV5SUK5J78o9YtPQRtGT8FDdDBkpAaIrjZ3-G1pzvWH2gP_bykoZA0S569cX9VFad5UA6SYyzDRDF44tTlrkWM0enY_9pdmlIUUWTLG0eCvSw55I86BX3diMAkhEm4SfjrQ-DLImflw6LzIX8XG1Sk5uJuM2hC-8BgIsk-gMbjj8xkmBlJFlk1y8FIxHXTYUuCRSXl5BHOCfZY2Q1tod7miHwAzAZ2GuDFCjbG-OCwbAFkZ7OW_tO-XwBsPDDpBCumogMkCoKKZ6QFSOcJwhLlik9xg6Qp81FJpE--Mw_XVGGmbAy3ivHkGgOKk-PWyx6R5GhdRLrxFFIP7NmjuBEhctBE7ah-hq1hNLorYsHWD9ael6XXceyt45cY0xe53cRtbfGF4Mwg1abDNY6FLeGzNeIGxD5HlO25S9b7W5Q; XSRF-TOKEN=CfDJ8PL4AaNuMwVFiNQ23RL0Qz1vUXxBYv3gCSx5ytS32yV7XFs6z0ctFaL79mS_R09hUhuprVGfAZvyPkCdx4oisLiObJCzrXTMRV4Y_jqxr-ENnPqiR0PkTPkvpjmp4cMOghPUXxdfsgZttlE1ah5ahOCtPrvmyGsiqmoqDDNFwPv0LBP317O3Vi4_dm-OtTmdig; idsrv.session=5276D5EFBDD0DFAA31CAAA5E85B31CFD; .AspNetCore.Antiforgery.C76e19UGF2Y=CfDJ8PL4AaNuMwVFiNQ23RL0Qz2lLiY4F2LeVaeM2wS2if2C2T8h4T4RIbuEGOOmP9yXnxgv-niJ2iLlVWtDkcdSOIBpoYhnWW8iJWchLQiElZApb08Gqez6tHO7_h-0NvhVrXX7RN40O-GRV_8INr8eTpg
Origin: https://localhost:44301
Referer: https://localhost:44301/ui/playground
Content-Length: 185

```

**Comment by Shane32** [comment]
Please see the GraphQL specification which defines this requirement:

https://spec.graphql.org/June2018/#sec-Names

To disable name validation, you may change `GlobalSwitches.NameValidation`.  However, GraphQL queries will not parse correctly with a space in the name, so it is of little practical use in this case.

**Comment by SpiraMira** [comment]
Thanks for the clarification!
