### ISSUE TITLE
Exception when I iterate through the types of a schema before defining any resolvers etc

### ISSUE THREAD

**Issue by njlr** [graphql-dotnet/graphql-dotnet#3449]
I am trying to read a string as a `Schema` and then print out all of the type names in that schema. 

Here is my script:

```fsharp
#r "nuget: GraphQL, 7.2.1"
#r "nuget: GraphQL.SystemTextJson"

open GraphQL
open GraphQL.Types
open GraphQL.SystemTextJson

let definition =
  """type User {
  id : ID!
  handle : String!
  bio : String
  karma : Int!
}

union CommentParent = Post | Comment

type Post {
  id : ID!
  created : String!
  title : String!
  url : String!
  posterId : ID!
  poster : User
  karma : Int!
}

type Comment {
  id : ID!
  created : String!
  commenterId : ID!
  commenter : User
  parent : CommentParent
  content : String!
  karma : Int!
}

type Query {
  posts(page : Int! = 0) : [Post!]!
  profile(id : ID!) : User
}
"""

let schema = Schema.For(definition)

printfn "Found these GraphQL types: "

for graphQLType in schema.AllTypes do
  match graphQLType with
  | :? GraphQL.Types.INamedType as namedType ->
    printfn $" - {namedType.Name}"
  | _ -> ()

printfn "Done. "
```

It throws an error:

```
System.InvalidOperationException: Union type 'CommentParent' does not provide a 'resolveType' function and possible Type 'CommentParent' does not provide a 'isTypeOf' function. There is no way to resolve this possible type during execution.
   at GraphQL.Types.SchemaTypes.ApplyTypeReference(IGraphType type) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 842
   at GraphQL.Types.SchemaTypes.ApplyTypeReferences() in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 790
   at GraphQL.Types.SchemaTypes.Initialize(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 225
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider, IEnumerable`1 graphTypeMappings) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 133
   at GraphQL.Types.SchemaTypes..ctor(ISchema schema, IServiceProvider serviceProvider) in /_/src/GraphQL/Types/Collections/SchemaTypes.cs:line 118
   at GraphQL.Types.Schema.CreateSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 471
   at GraphQL.Types.Schema.CreateAndInitializeSchemaTypes() in /_/src/GraphQL/Types/Schema.cs:line 442
   at GraphQL.Types.Schema.Initialize() in /_/src/GraphQL/Types/Schema.cs:line 210
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in /home/njlr/Repro.fsx:line 8
Stopped due to error
```

Is there a way to examine the types of a schema parsed from a string?

**Comment by Shane32** [comment]
You can parse the SDL using the GraphQL.Parser project and iterate through the type definitions there.  Call `Parser.Parse(definitions)`

**Comment by njlr** [comment]
> You can parse the SDL using the GraphQLParser project and iterate through the type definitions there. Call `GraphQLParser.Parser.Parse(definitions)`

Works a treat!

```fsharp
#r "nuget: GraphQL, 7.2.1"
#r "nuget: GraphQL.SystemTextJson"

open GraphQLParser
open GraphQLParser.AST

let definition =
  """type User {
  id : ID!
  handle : String!
  bio : String
  karma : Int!
}

union CommentParent = Post | Comment

type Post {
  id : ID!
  created : String!
  title : String!
  url : String!
  posterId : ID!
  poster : User
  karma : Int!
}

type Comment {
  id : ID!
  created : String!
  commenterId : ID!
  commenter : User
  parent : CommentParent
  content : String!
  karma : Int!
}

type Query {
  posts(page : Int! = 0) : [Post!]!
  profile(id : ID!) : User
}
"""

let doc = Parser.Parse(definition)

printfn "Found these GraphQL types: "

for node in doc.Definitions do
  match node with
  | :? GraphQLTypeDefinition as typeDefinition ->
    printfn $" - {typeDefinition.Name}"
  | _ -> ()

```

```
Found these GraphQL types: 
 - User
 - CommentParent
 - Post
 - Comment
 - Query

```
