### ISSUE TITLE
GetDefaultName do not strip out "@"

### ISSUE THREAD

**Issue by njlr** [graphql-dotnet/graphql-dotnet#3472]
This issue is relevant to F# users. 

This script creates a new `InputObjectGraphType`:

```fsharp
#r "nuget: GraphQL, 7.2.1"

open GraphQL.Types

type UserInput =
  {
    Username : string
    Email : string option
  }

let userInputGraphType =
  {
    new InputObjectGraphType<UserInput>() with
      override this.ParseDictionary(values) =
        {
          Username =
            values["username"] :?> string
          Email =
            values["email"]
            |> Option.ofObj
            |> Option.map (fun x -> x :?> string)
        }
  }

// Never reached
userInputGraphType.Name <- "UserInput"
```

However, running it will throw this exception:

```
System.ArgumentOutOfRangeException: A type name must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but 'userInputGraphType@12' does not. (Parameter 'name')
   at GraphQL.Utilities.NameValidator.<ValidateDefault>g__ThrowMatchError|2_0(<>c__DisplayClass2_0& ) in /_/src/GraphQL/Utilities/NameValidator.cs:line 50
   at GraphQL.Utilities.NameValidator.ValidateDefault(String name, NamedElement type) in /_/src/GraphQL/Utilities/NameValidator.cs:line 45
   at GraphQL.Utilities.NameValidator.ValidateName(String name, NamedElement type) in /_/src/GraphQL/Utilities/NameValidator.cs:line 13
   at GraphQL.Types.GraphType.SetName(String name, Boolean validate) in /_/src/GraphQL/Types/GraphType.cs:line 67
   at GraphQL.Types.GraphType..ctor() in /_/src/GraphQL/Types/GraphType.cs:line 25
   at GraphQL.Types.ComplexGraphType`1..ctor() in /_/src/GraphQL/Types/Composite/ComplexGraphType.cs:line 18
   at GraphQL.Types.InputObjectGraphType`1..ctor()
   at FSI_0002.userInputGraphType@12..ctor()
   at <StartupCode$FSI_0002>.$FSI_0002.main@() in /runner/Scratch.fsx:line 11
Stopped due to error
```

The issue is that F# names an object expression (anonymous class) using an `"@"`. AFAIK the user cannot control this name. 

The code here does not appear to strip out `"@"`: https://github.com/graphql-dotnet/graphql-dotnet/blob/be283cfe0e0b95b237be7981999de23bbaac16cb/src/GraphQL/Types/GraphType.cs#L39-L59

**Comment by sungam3r** [comment]
😮 I do not know F# and have never used it before but I think I understand a concept of mentioned object expression (anonymous class). Would you like to submit PR to fix it?

**Comment by sungam3r** [comment]
Ref: https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/object-expressions

**Comment by sungam3r** [comment]
I think you can just replace `@` with `_`.

**Comment by njlr** [comment]
> I think you can just replace `@` with `_`.

Yep, happy to send a PR.
