### ISSUE TITLE
GraphQL 0.17.0 looks to have a regression around serialization of errors

### ISSUE THREAD

**Issue by bittercoder** [graphql-dotnet/graphql-dotnet#371]
Have recently updated from GraphQL 0.15.1.678 to 0.17.0 and it looks like there has been a regression in the serialisation of errors.

It can be reproduced by just adding a throw into a field resolver callback for a query e.g.

	FieldAsync<SomeType>("things", resolve: async context => { throw new Exception(); })

If I roll back to 0.15.x then it will correctly serialize the errors in the response.

Here is the stack trace when it attempts graphql-dotnet tries to serialise the errors:

```
Newtonsoft.Json.JsonWriterException: Token StartArray in state Object would result in an invalid JSON object. Path 'errors[0]'.
   at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
   at Newtonsoft.Json.JsonWriter.InternalWriteStart(JsonToken token, JsonContainerType container)
   at Newtonsoft.Json.JsonTextWriter.WriteStartArray()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at GraphQL.ExecutionResultJsonConverter.<>c__DisplayClass2_0.<writeErrors>b__0(ExecutionError error)
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action)
   at GraphQL.ExecutionResultJsonConverter.writeErrors(ExecutionErrors errors, JsonWriter writer, JsonSerializer serializer)
   at GraphQL.ExecutionResultJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at GraphQL.Http.DocumentWriter.Write(Object value)
```

Just wondering if this is a known issue or not?

**Comment by joemcbride** [comment]
You're the first to report it. Can you try 0.16.0 and/or 0.16.1 and see if you get the same issue?

**Comment by joemcbride** [comment]
Found the problem, fixing it.

**Comment by bittercoder** [comment]
Thanks heaps for fixing this issue@joemcbride  :+1:
