### ISSUE TITLE
Test on net9.0

### ISSUE THREAD

**Issue by sebastienros** [graphql-dotnet/graphql-dotnet#4020]
I am current facing an issue while porting Orchard Core to dotnet 9. All our tests work on 8 but there is a new runtime error with 9. We are multi-targeting to 8 and 9 in a branch.

```
System.ArgumentException: Type ContentItemType with name 'LinkMenuItem' does not implement interface MenuItemInterface with name 'MenuItem'. It has no field 'menuItemsList'.
         at GraphQL.GraphQLExtensions.IsValidInterfaceFor(IInterfaceGraphType iface, IObjectGraphType type, Boolean throwError) in /_/src/GraphQL/Extensions/GraphQLExtensions.cs:line 188
         at GraphQL.Types.ObjectGraphType`1.AddResolvedInterface(IInterfaceGraphType graphType) in /_/src/GraphQL/Types/Composite/ObjectGraphType.cs:line 56
```

This is probably a bug in our code, but this should show up with both frameworks, unless there is a new behavior in 9 that might not be expected. I think it would be safer to start testing this repos on 9 before it ships.

**Comment by sebastienros** [comment]
I found the issue which was related to a change in our code for net9.0.
I am closing this issue but it wouldn't hurt to prepare for 9.0 before it has shipped.

Thanks
