### ISSUE TITLE
dotnet core error

### ISSUE THREAD

**Issue by lusess123** [graphql-dotnet/graphql-dotnet#639]
```

Application startup exception: System.IO.FileLoadException: Could not load file or assembly 'GraphQL, Version=2.0.0.820, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest
definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'GraphQL, Version=2.0.0.820, Culture=neutral, PublicKeyToken=null'
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
```

**Comment by lusess123** [comment]
Thanks.   I have already settled the matter.
