### ISSUE TITLE
AppVeyor builds failing

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/graphql-dotnet#643]
Anyone want to investigate what's the reason? To me it looks like `npm --version` is crashing but might be wrong. Tested it on my own machine and didn't have similar problems with latest npm. 

Example: https://ci.appveyor.com/project/graphql-dotnet-ci/graphql-dotnet/build/2.0.0.890-fnnnwskk

```
Build started
git clone -q https://github.com/graphql-dotnet/graphql-dotnet.git C:\projects\graphql-dotnet
git fetch -q origin +refs/pull/642/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
npm install -g npm
C:\Users\appveyor\AppData\Roaming\npm\npm -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\appveyor\AppData\Roaming\npm\npx -> C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
npm@6.0.0 C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm
npm --version
C:\Users\appveyor\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:79
      let notifier = require('update-notifier')({pkg})
      ^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
Command exited with code 1
```

**Comment by OneCyrus** [comment]
what node version is it using? looks like the new npm 6 isn‘t compatible with this node version.

**Comment by OneCyrus** [comment]
ok that looks wrong in appveyor.yml

```
install:
  - npm install -g npm
  - npm --version
  - ps: Install-Product node LTS
  - node --version
  - dotnet --version
```

```ps: Install-Product node LTS``` should be the first install action.
