### ISSUE TITLE
GraphTypesLookup._types modified while enumerating.

### ISSUE THREAD

**Issue by MartinLorensen** [graphql-dotnet/graphql-dotnet#67]
From time to time I get the exception bellow. I am not sure exactly why this happen, but it looks like a concurrency issue as the code in the indexer only iterates the collection without modifying it.

The easy fix would be to replace the _types Dictionary<,> with a ConcurrentDictionary<,>, but as I do not fully understand the problem, I am not sure that is the right solution.

It could obviously be my code that does something wrong - but from a stacktrace with only System and GraphQL namespaces present and with the high degree of thread-awareness in GraphQL, I have a hard time figuring out where to start search for the problem in our code base.

 - Is it the intention that the _field dictionary should be fully populated before used?
 - Should each thread accessing the GraphTypeLookup object have it's own instance?
 - Should it have been guarded with semaphors/be concurrent?
 - Or do I miss something obvious?

```
{
  "message": "An error has occurred.", 
  "exceptionMessage": "Collection was modified; enumeration operation may not execute.",
  "exceptionType": "System.InvalidOperationException",
  "stackTrace": "
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at GraphQL.Types.GraphTypesLookup.get_Item(Type type) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 64
   at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 182
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass12_0.<AddType>b__0(FieldType field) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 116
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in C:\Home\projects\graphql-dotnet\src\GraphQL\EnumerableExtensions.cs:line 29
   at GraphQL.Types.GraphTypesLookup.AddType(GraphType type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 127
   at GraphQL.Types.Schema.<EnsureLookup>b__24_0(String name, GraphType graphType, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\Schema.cs:line 116
   at GraphQL.Types.ListGraphType.CollectTypes(TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\ListGraphType.cs:line 28
   at GraphQL.Types.GraphTypesLookup.AddType(GraphType type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 111
   at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 187
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass12_0.<AddType>b__0(FieldType field) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 116
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in C:\Home\projects\graphql-dotnet\src\GraphQL\EnumerableExtensions.cs:line 29
   at GraphQL.Types.GraphTypesLookup.AddType(GraphType type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 127
   at GraphQL.Types.GraphTypesLookup.AddTypeIfNotRegistered(Type type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 187
   at GraphQL.Types.GraphTypesLookup.<>c__DisplayClass12_0.<AddType>b__0(FieldType field) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 116
   at GraphQL.EnumerableExtensions.Apply[T](IEnumerable`1 items, Action`1 action) in C:\Home\projects\graphql-dotnet\src\GraphQL\EnumerableExtensions.cs:line 29
   at GraphQL.Types.GraphTypesLookup.AddType(GraphType type, TypeCollectionContext context) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\GraphTypesLookup.cs:line 127
   at GraphQL.Types.Schema.EnsureLookup() in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\Schema.cs:line 119
   at GraphQL.Types.Schema.FindType(Type type) in C:\Home\projects\graphql-dotnet\src\GraphQL\Types\Schema.cs:line 78
   at GraphQL.DocumentExecuter.<>c__DisplayClass11_0.<GetArgumentValues>b__0(Dictionary`2 acc, QueryArgument arg) in C:\Home\projects\graphql-dotnet\src\GraphQL\Execution\DocumentExecuter.cs:line 307
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at GraphQL.DocumentExecuter.<ResolveField>d__8.MoveNext() in C:\Home\projects\graphql-dotnet\src\GraphQL\Execution\DocumentExecuter.cs:line 150
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.EnumerableExtensions.<>c__DisplayClass3_0`4.<<ToDictionaryAsync>b__0>d.MoveNext() in :line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.EnumerableExtensions.<ToDictionaryAsync>d__3`4.MoveNext() in :line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.DocumentExecuter.<ExecuteFields>d__7.MoveNext() in :line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GraphQL.DocumentExecuter.<ExecuteAsync>d__4.MoveNext() in C:\Home\projects\graphql-dotnet\src\GraphQL\Execution\DocumentExecuter.cs:line 67
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"}
```

**Comment by joemcbride** [comment]
Does this happen on startup or after it has been running for a while?

It is currently intended for the `GraphTypesLookup` to be fully populated before execution, though I could see the case of this happening.  I don't think we are explicitly "warming up" the lookup cache before execution.

* I don't think each thread needs its own copy.
* There could be a bug where the types aren't getting populated during the normal `EnsureLookup` phase in the `Schema` class.
* Assuming you don't have the above issue, you can "warm up" the `GraphTypesLookup` cache before executing any queries.  Perhaps the easiest way to do this now would be to call `ISchema.FindType("someType")`, or `Schema.EnsureLookup()`.  `EnsureLookup` is currently `public`, though it should probably be `private` or `internal`.

You can use the new `SchemaPrinter` or an introspection query to print out what the "default" registration is.

**Comment by joemcbride** [comment]
I should mention, the JS project has a way to "pre-register" custom types.  We don't have that feature yet, though it would be fairly simple to add.

**Comment by MartinLorensen** [comment]
Ok, now I think I understand what is going on.

The easy fix/workaround is for me to add EnsureLookup in the end of the constructor of my Schema-derived class.

Multiple places in the Schema class EnsureLookup is called. I assume multiple threads can call these methods, possibly concurrently. EnsureLookup is not thread safe since it test if _lookup is set and right after set it and continues to modify it. I see 3 reasonable changes:

A) No locking - possibly do the work multiple times:
```
      if (this._lookup != null)
        return;
      var lookup = new GraphTypesLookup();
      ...initialize lookup...
      this._lookup = lookup;
```
B) Local locking
```
   readonly object myLock = new object();
    ...
   lock(myLock)
   {
      if (this._lookup != null)
        return;
      this._lookup = new GraphTypesLookup();
      ...initialize _lookup...
   }
```

C) Use Lazy, remove calls to EnsureLookup.

```
   private readonly Lazy<GraphTypesLookup> _lookup = new Lazy<GraphTypesLookup>(CreateLookup);
   ...
   private GraphTypeLookup CreateLookup()
   {
      var lookup = new GraphTypesLookup();
      ...initialize lookup...
      return lookup;
   }

```

Depending on call patterns A might be faster, but B and C should be very similar. I would probably go for C.

**Comment by joemcbride** [comment]
I like the Lazy route as well, will make that change.
