### ISSUE TITLE
Getting Could not load file or assembly GraphQL, Version=2.0.0.868 Error

### ISSUE THREAD

**Issue by RehanSaeed** [graphql-dotnet/graphql-dotnet#779]
## Description

I'm trying to upgrade my GraphQL.NET Boxed project template to 2.0. I'm getting the following error at runtime:

```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not load file or assembly 'GraphQL, Version=2.0.0.868, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
  Source=AuthorizationFalse
  StackTrace:
   at AuthorizationFalse.CustomServiceCollectionExtensions.AddCustomGraphQL(IServiceCollection services, IHostingEnvironment hostingEnvironment) in C:\Users\Rehan\AppData\Local\Temp\a1d78643-3989-42ec-95ae-88701ed70453\AuthorizationFalse\CustomServiceCollectionExtensions.cs:line 134
   at AuthorizationFalse.Startup.ConfigureServices(IServiceCollection services) in C:\Users\Rehan\AppData\Local\Temp\a1d78643-3989-42ec-95ae-88701ed70453\AuthorizationFalse\Startup.cs:line 46
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at AuthorizationFalse.Program.Main(String[] args) in C:\Users\Rehan\AppData\Local\Temp\a1d78643-3989-42ec-95ae-88701ed70453\AuthorizationFalse\Program.cs:line 17
```

### Steps to reproduce

These are my package references:

```
<PackageReference Include="GraphQL" Version="2.0.0" />
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.1.0-alpha0027" />
<PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.1.0-alpha0027" />
<PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.1.0-alpha0027" />
```

### Expected result

I shouldn't get file not found errors.

**Comment by joemcbride** [comment]
This is due to how the server project set the version.  It should be fixed with this PR https://github.com/graphql-dotnet/server/pull/145
