### ISSUE TITLE
GraphQL Version 2.0.0 - Version mismatch between assembly & manifest?

### ISSUE THREAD

**Issue by KreativJos** [graphql-dotnet/graphql-dotnet#783]
## Description

```
An unhandled exception of type 'System.IO.FileLoadException' occurred in System.Private.CoreLib.dll: 'Could not load file or assembly 'GraphQL, Version=2.0.0.868, Culture=neutral, PublicKeyToken=null'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'
   at test2.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env) in C:\Workbench\GraphQL\test2\Startup.cs:line 56
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.Internal.AutoRequestServicesStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.<StartAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at test2.Program.Main(String[] args) in C:\Workbench\GraphQL\test2\Program.cs:line 17
```
### Steps to reproduce

1. Create a new .net core webapi project.
2. Add GraphQL v2.0.0
3. Add startup stuff
4. Run the project

### Environment

On: Windows 10
.net core 2.1
Previously used GQL 2.0.0-alpha-818

**Comment by KreativJos** [comment]
Ah, guessing now this belongs to the GQL-server repo:

> "GraphQL.Server.Transports.AspNetCore/3.1.0-alpha0027": {
>         "type": "package",
>         "dependencies": {
>           "GraphQL": "[2.0.0-alpha-868, 2.1.0)",

**Comment by joemcbride** [comment]
Yes - this was fixed here: https://github.com/graphql-dotnet/server/pull/145

Waiting on official release here: https://github.com/graphql-dotnet/server/pull/146

**Comment by KreativJos** [comment]
Ah, sorry, couldn't find it via the search. I think I might have had a typo.
Thnx!
