### ISSUE TITLE
Memory stream is not expandable

### ISSUE THREAD

**Issue by AmbroiseCouissin** [graphql-dotnet/graphql-dotnet#875]
Hi!

## Description

For big responses, I get the following error:

```
Memory stream is not expandable
```

Stacktrace:

```
An unhandled exception has occurred while executing the request.
System.NotSupportedException: Memory stream is not expandable.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at GraphQL.Http.HttpResponseStreamWriter.FlushInternal(Boolean flushEncoder)
   at GraphQL.Http.HttpResponseStreamWriter.Write(String value)
   at Newtonsoft.Json.Utilities.JavaScriptUtils.WriteEscapedJavaScriptString(TextWriter writer, String s, Char delimiter, Boolean appendDelimiters, Boolean[] charEscapeFlags, StringEscapeHandling stringEscapeHandling, IArrayPool`1 bufferPool, Char[]& writeBuffer)
   at Newtonsoft.Json.JsonTextWriter.WriteEscapedString(String value, Boolean quote)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerProxy.SerializeInternal(JsonWriter jsonWriter, Object value, Type rootType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at GraphQL.ExecutionResultJsonConverter.WriteData(ExecutionResult result, JsonWriter writer, JsonSerializer serializer)
   at GraphQL.ExecutionResultJsonConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at GraphQL.Http.DocumentWriter.WriteAsync[T](Stream stream, T value)
   at GraphQL.Http.DocumentWriter.WriteAsync[T](T value)
   at GraphQL.Http.DocumentWriterExtensions.WriteToStringAsync(IDocumentWriter writer, ExecutionResult value, Encoding encoding)
   at GraphQL.Http.DocumentWriter.Write(Object value)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.WriteResponseAsync(HttpContext context, IDocumentWriter writer, ExecutionResult result)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at GraphQL.Server.Transports.WebSockets.GraphQLWebSocketsMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce

It gets triggered when the response is bigger than 1024KB.  Is it because of the DefaultBufferSize ?

Thanks!

**Comment by joemcbride** [comment]
It could possibly be related, though I believe the default is bigger than 1024KB.  

For that code path it should be getting this buffer size:

https://github.com/graphql-dotnet/graphql-dotnet/blob/0917a2c8c3f7fc078ce4429f0edc3b051ef949c9/src/GraphQL/Http/DocumentWriter.cs#L24

Can you try switching to using the new `WriteAsync` directly?  That would look something like:

```csharp
private async Task WriteResponseAsync(
  IDocumentWriter writer,
  HttpContext context,
  ExecutionResult result)
{
  context.Response.ContentType = "application/json";
  await writer.WriteAsync(context.Response.Body, result);
}
```

Thoughts @DSilence?

**Comment by DSilence** [comment]
@AmbroiseCouissin , @joemcbride, Yep, that should solve the issue. The hard limit should only be valid for websocket requests, but since the backwards-compatible Write method is using the same code as well, it's affected by this change.
As a side note, I probably should have left the implementation of old method as is. I'll make a quick PR to fix it.

**Comment by DSilence** [comment]
I'm also experimenting on the server project with alternative Stream API for writing websockets. Something like this
```csharp
 public class WebsocketWriterStream : Stream
    {
        private readonly WebSocket _webSocket;

        public WebsocketWriterStream(WebSocket webSocket)
        {
            _webSocket = webSocket;
        }

        public override Task WriteAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            return _webSocket.SendAsync(new ArraySegment<byte>(buffer, offset, count), WebSocketMessageType.Text, false,
                cancellationToken);
        }

        public override Task FlushAsync(CancellationToken cancellationToken)
        {
            return _webSocket.SendAsync(new ArraySegment<byte>(Array.Empty<byte>()), WebSocketMessageType.Text, true, cancellationToken);
        }
}
```
This way the whole buffered thing will not actually be needed, websockets will support messages of any size, and DocumentWriter could be reduced to a single method.

**Comment by joemcbride** [comment]
@DSilence can you talk to why there is a hard limit currently?  If that is specific to websockets we should probably make that explicit.

**Comment by AmbroiseCouissin** [comment]
On our side, I was wrong about the limit of 1024KB. It was much bigger.

**Comment by DSilence** [comment]
@joemcbride There is a hard limit on ArrayPool.Shared as specified here (https://adamsitnik.com/Array-Pool/). It's used in my implementation to pool the byte arrays for DocumentWriter method that's supposed to write to sockets. The hard limit though should be 1mb, not 1024KB. 
The new, WriteAsync method should work just fine and should not have any limits.
At the moment, I'm working on server project to possibly have a stream-based response writing. For the time being, I've created a PR which restores the old implementation for the method that writes to string to avoid any explicit limits.
