### ISSUE TITLE
Cannot convert value to AST: System.Collections.Generic.Dictionary

### ISSUE THREAD

**Issue by rose-a** [graphql-dotnet/graphql-dotnet#877]
I'm trying to create an implementation of [IGraphQLClient](https://github.com/graphql-dotnet/graphql-client/blob/master/src/GraphQL.Client/IGraphQLClient.cs) to directly execute an `ISchema` locally (without networking etc.), the main purpose for this is unit testing.

<details><summary>My current Implementation of `GraphQLLocalClient`</summary>

```c#
/// An <see cref="IGraphQLClient"/> which directly executes queries on the supplied schema
/// </summary>
public class GraphQLLocalClient: IGraphQLClient
{
    private readonly ISchema _schema;
    private readonly IDocumentExecuter _executer;

    public static readonly JsonSerializerSettings VariablesSerializerSettings = new JsonSerializerSettings
    {
        Formatting = Formatting.Indented,
        DateTimeZoneHandling = DateTimeZoneHandling.Local,
        ContractResolver = new CamelCasePropertyNamesContractResolver()
    };

    /// <summary>
    /// Creates a new <see cref="GraphQLLocalClient"/> for the supplied schema
    /// </summary>
    /// <param name="schema"></param>
    protected GraphQLLocalClient(ISchema schema)
    {
        _schema = schema;
        if(!_schema.Initialized) _schema.Initialize();

        _executer = new DocumentExecuter();
    }

    /// <inheritdoc />
    public Task<GraphQLResponse> SendQueryAsync(GraphQLRequest request, CancellationToken cancellationToken = new CancellationToken())
        => _executeQueryAsync(request, cancellationToken);

    /// <inheritdoc />
    public Task<GraphQLResponse> SendMutationAsync(GraphQLRequest request, CancellationToken cancellationToken = new CancellationToken())
        => _executeQueryAsync(request, cancellationToken);

    private async Task<GraphQLResponse> _executeQueryAsync(GraphQLRequest request,
        CancellationToken cancellationToken)
    {

        var inputs = request.Variables != null
            ? (JObject.FromObject(request.Variables, JsonSerializer.Create(VariablesSerializerSettings)) as JObject).ToInputs()
            : null;

        var result = await _executer.ExecuteAsync(options =>
        {
            options.Schema = _schema;
            options.OperationName = request.OperationName;
            options.Query = request.Query;
            options.Inputs = inputs;
            options.CancellationToken = cancellationToken;
        }).ConfigureAwait(false);

        return JToken
            .FromObject(result)
            .ToObject<GraphQLResponse>();
    }

    /// <inheritdoc />
    [Obsolete("Not yet implemented")]
    public async Task<IGraphQLSubscriptionResult> SendSubscribeAsync(GraphQLRequest request, CancellationToken cancellationToken = new CancellationToken())
    {
        throw new System.NotImplementedException();
    }

    /// <inheritdoc />
    public void Dispose()
    {}
}

/// <inheritdoc/>
public class GraphQLLocalClient<TSchema> : GraphQLLocalClient where TSchema : ISchema
{
    /// <summary>
    /// Creates a new <see cref="GraphQLLocalClient{TSchema}"/> for the supplied schema
    /// </summary>
    /// <param name="schema"></param>
    public GraphQLLocalClient(TSchema schema) : base(schema)
    {}
}
```
</details>

<details><summary>The mutation and types are defined like so</summary>

```c#
/// <summary>
/// Test mutation class
/// </summary>
public class UnitTestMutation : ObjectGraphType
{
    public static readonly TestingInput TestingInput = new TestingInput{Id = 1337, Name = "Hallo Welt"};

    public UnitTestMutation()
    {
        Name = "HtApiUnitTestMutation";

        Field<BooleanGraphType>()
            .Name("testInputObject")
            .Description("returns true if the input object was successfully parsed and equals the predefined object")
            .Argument<TestingInputType>("input", "the input object")
            .Resolve(ctx =>
            {
                var input = ctx.ConvertArgumentToObject<TestingInput>("input");

                return input?.Id == TestingInput.Id && input.Name == TestingInput.Name;
            });
    }
}

public class TestingInputType: InputObjectGraphType<TestingInput>
{
    public TestingInputType()
    {
        Name = "TestingInput";

        Field<IntGraphType>().Name("id");
        Field<StringGraphType>().Name("name");
    }
}

public class TestingInput
{
    public int Id { get; set; }
    public string Name { get; set; }
}
```
</details>

Now I'm trying to run the following query against the schema:

```graphql
mutation($input: TestingInput){
    testInputObject(input: $input)
}
```

```c#
[TestMethod]
public async Task TestInputObjectMutation()
{
    var client = _container.GetInstance<IGraphQLClient>();

    GraphQLRequest request = new GraphQLRequest { Query = _RETURNINPUT_QUERY, Variables = new { input = UnitTestMutation.TestingInput } };
    var response = await client.SendMutationAsync(request).ConfigureAwait(false);

    Assert.IsFalse(response.HasErrors(), $"query failed with errors: {JsonConvert.SerializeObject(response.Errors)}");

    Assert.IsTrue((bool)response.Data.testInputObject, "failed to parse input object");
}
```

which results in the following `ExecutionError`:

```
Cannot convert value to AST: System.Collections.Generic.Dictionary`2[System.String,System.Object]

StackTrace:
   at GraphQL.GraphQLExtensions.AstFromValue(Object value, ISchema schema, IGraphType type)
   at GraphQL.Execution.ExecutionHelper.GetVariableValue(Document document, ISchema schema, VariableDefinition variable, Object input)
   at GraphQL.Execution.ExecutionHelper.GetVariableValues(Document document, ISchema schema, VariableDefinitions variableDefinitions, Inputs inputs)
   at GraphQL.DocumentExecuter.BuildExecutionContext(ISchema schema, Object root, Document document, Operation operation, Inputs inputs, Object userContext, CancellationToken cancellationToken, Metrics metrics, IEnumerable`1 listeners, Boolean throwOnUnhandledException)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)
```

The `Inputs` object looks like this:

![grafik](https://user-images.githubusercontent.com/15836594/47437688-62b0d100-d7a9-11e8-856e-810f00044161.png)

Querying the same schema via network works. I've checked them both to contain the same types. 
Also the `Inputs` object is identical.

Does anybody have any idea how this might happen?

**Comment by rose-a** [comment]
Dammit, I used the wrong query string variable... took me 2 hours and writing this issue to figure that out -_-
