### ISSUE TITLE
Expected non-null value, resolve delegate return null

### ISSUE THREAD

**Issue by mike-niemand** [graphql-dotnet/graphql-dotnet#930]
Hi All,

This is no doubt related to: https://github.com/graphql-dotnet/graphql-dotnet/issues/807

When executing a query e.g. _{menu: {menuId, nenuName}}_ the document executor throws: 

_Expected non-null value, resolve delegate return null for $GraphQL.Types.ComplexGraphType`1[DelFornoAPI.Models.Customer]_

This type is unrelated to the query but does exist as a field in another type i.e.:

```
 public class CustomerOrderType : ObjectGraphType<VMCustomerOrder>
    {
        public CustomerOrderType()
        {
            Name = "CustomerOrderType";
            Field(x => x.CustomerOrderId);
            Field(x => x.FranchiseId);
            Field(x => x.Instruction, true, typeof(StringGraphType));
            Field(x => x.Customer, true, typeof(ComplexGraphType<Customer>));
        }
    }
```
It is however set to allow nullable.

Why is it attempting to validate this type as not null when it is unrelated to the query?

**Comment by joemcbride** [comment]
```
Field(x => x.Customer, true, typeof(ComplexGraphType<Customer>));
```

This won't work.  `ComplexGraphType` is an abstract base type.  Arguably that perhaps should be an internal type.  You need to create a class that inherits from `ObjectGraphType`.

**Comment by mike-niemand** [comment]
Thanks for the response Joe, it's much appreciated. I'm still having trouble even after casting Customer this to an ObjectGraphType.

_{System.InvalidOperationException: Expected non-null value, resolve delegate return null for "$GraphQL.Types.ObjectGraphType`1[DelFornoAPI.Models.Customer]"
   at GraphQL.GraphQLExtensions.BuildNamedType(Type type, Func`2 resolve)
   at GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at GraphQL.Types.Schema.get_AllTypes()
   at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)}_

I'm not querying this type at all though?

**Comment by mike-niemand** [comment]
I have the following registered in the schema:

```
public class CustomerType : ObjectGraphType<Customer>
    {
        public CustomerType()
        {
            Name = "Customer";
            Field(x => x.CustomerId);
            Field(x => x.Firstname);
            Field(x => x.Surname);
        }
    }
```

and

```
public class CustomerOrderType : ObjectGraphType<CustomerOrder>
    {
        public CustomerOrderType()
        {
            Name = "CustomerOrderType";
            Field(x => x.CustomerOrderId);
            Field(x => x.FranchiseId);
            Field(x => x.Customer, true, typeof(ObjectGraphType<CustomerType>));
        }
    }
```

Which throws: 

_{GraphQL.ExecutionError: Expected non-null value, resolve delegate return null for "$GraphQL.Types.ObjectGraphType`1[DelFornoAPI.GraphQL.CustomerType]" ---> System.InvalidOperationException: Expected non-null value, resolve delegate return null for "$GraphQL.Types.ObjectGraphType`1[DelFornoAPI.GraphQL.CustomerType]"
   at GraphQL.GraphQLExtensions.BuildNamedType(Type type, Func`2 resolve)
   at GraphQL.Types.GraphTypesLookup.HandleField(Type parentType, FieldType field, TypeCollectionContext context)
   at GraphQL.Types.GraphTypesLookup.AddType(IGraphType type, TypeCollectionContext context)
   at GraphQL.Types.GraphTypesLookup.Create(IEnumerable`1 types, IEnumerable`1 directives, Func`2 resolveType, IFieldNameConverter fieldNameConverter)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at GraphQL.Types.Schema.get_AllTypes()
   at GraphQL.Instrumentation.FieldMiddlewareBuilder.ApplyTo(ISchema schema)
   at GraphQL.DocumentExecuter.ExecuteAsync(ExecutionOptions options)_

I'm clearly confused as I don't understand why it's expected to be non-null?

**Comment by joemcbride** [comment]
Change this:


```csharp
Field(x => x.Customer, true, typeof(ObjectGraphType<CustomerType>));
```

To this:

```csharp
Field(x => x.Customer, true, typeof(CustomerType));
```

**Comment by mike-niemand** [comment]
Yes. That solved it and also taught me a little more about what you've done. Thank-you so much. What a great project.

**Comment by joemcbride** [comment]
One thing that could perhaps be done is to throw an error if you pass an object that inherits from `IGraphType` to the `ObjectGraphType`/`ComplexGraphType` generic argument.

**Comment by mike-niemand** [comment]
I'm sure that would help. Was this a change implemented in 2.x? I had it working fine before I moved to 2.4 although this is a much better.

**Comment by joemcbride** [comment]
I'm not sure.  That should have never worked.  That is somehow was is a mystery to me.

**Comment by sungam3r** [comment]
@mike-niemand Is this issue still actual?

**Comment by mike-niemand** [comment]
> @mike-niemand Is this issue still actual?

I don't have this issue anymore.
