### ISSUE TITLE
__typename not working with unions

### ISSUE THREAD

**Issue by Jefffrey** [graphql-dotnet/graphql-dotnet#960]
## Description

I have a mutation like:

```
mutation {
  signIn(...) {
    ... on TypeA {
      __typename
      fieldA
    }
    ... on TypeB {
      __typename
    }
    ... on TypeC {
      __typename
    }
  }
}
```

that seems to compile (at the GraphQL level) because `graphql-dotnet` answers with:

```
{
  "data": {
    "signIn": {}
  }
}
```

if the response is `TypeB` or `TypeC` and:

```
{
  "data": {
    "signIn": { "fieldA": ... }
  }
}
```

if the response is `TypeA`.

The `__typename` is ignored.

### Steps to reproduce

 - Define a union type as the response for a mutation or query
 - Query/mutate in order to get the response
 - Try to add `__typename` to the list of fields

### Expected result

The type name should be returned as [per spec](https://graphql.org/learn/queries/#meta-fields).

### Actual result

The `__typename` is ignored.

### Environment

dotnet 2.2, graphql-dotnet 2.4.0

### Extra

`__typename` seems to work fine with other single types.

In the case of unions instead using `__typename` at the union level:

```
mutation {
  signIn(...) {
    __typename
    ... on TypeA {
      __typename
      fieldA
    }
    ... on TypeB {
      __typename
    }
    ... on TypeC {
      __typename
    }
  }
}
```

gives you:

```
System.NullReferenceException: Object reference not set to an instance of an object.
         at GraphQL.Introspection.TypeNameMetaFieldType.<>c.<.ctor>b__0_0(ResolveFieldContext context)
         at GraphQL.Resolvers.FuncFieldResolver`1.GraphQL.Resolvers.IFieldResolver.Resolve(ResolveFieldContext context)
         at GraphQL.Execution.ExecutionStrategy.ExecuteNodeAsync(ExecutionContext context, ExecutionNode node)
```

**Comment by Jefffrey** [comment]
Apparently this was caused by an incorrect schema definition. Specifically `TypeB` and `TypeC` where defined as `ObjectGraphType`s of themselves due to a typo.
